/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.sgb.vistas;

import static com.biosis.sgb.Application.BORDE_FONDO;
import static com.biosis.sgb.Application.ESTILO1;
import static com.biosis.sgb.Application.ESTILO4;
import static com.biosis.sgb.Application.ESTILO6;
import static com.biosis.sgb.Application.FORMATO_TIMESTAMP;
import static com.biosis.sgb.controlador.Controlador.NUEVO;
import com.biosis.sgb.controlador.EventoControlador;
import com.biosis.sgb.entidades.Usuario;
import com.biosis.sgb.info.GestorAcceso;
import static com.biosis.sgb.info.GestorAcceso.USUARIO_ACCESO;
import com.biosis.sgb.info.Monitor;
import com.biosis.sgb.info.UsuarioActivo;
import com.biosis.sgb.util.ButtonTabComponent;
import com.biosis.sgb.util.ControlAcceso;
import java.awt.Color;
import java.awt.Component;
import java.util.Date;
import org.apache.log4j.Logger;

/**
 *
 * @author Francis
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private static final Logger LOG = Logger.getLogger(Principal.class.getName());
    
    public Principal() {
        initComponents();
        initComponents2();
//        iniciarTab(0);
        mostrarInformacion(UsuarioActivo.getUsuario());
        guardarInformacionConexion(UsuarioActivo.getUsuario());        
        pnlBienvenida.setBorder(BORDE_FONDO);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlBienvenida = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblConexion = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnConsulta = new javax.swing.JButton();
        btnEjemplar = new javax.swing.JButton();
        btnPrestamo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuRegistroLibro = new javax.swing.JMenuItem();
        mnuRegistroEjemplar = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuRegistroAutor = new javax.swing.JMenuItem();
        mnuRegistroEditorial = new javax.swing.JMenuItem();
        mnuRegistroMateria = new javax.swing.JMenuItem();
        mnuRegistroTema = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnuPersona = new javax.swing.JMenuItem();
        mnuPrestamo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuReporteEjemplar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        tabPrincipal.setFont(ESTILO1);

        pnlBienvenida.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new Color(0,0,0,65));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 35, 20));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido al sistema de gestión de biblioteca");
        jPanel3.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 5, 0));

        lblUsuario.setFont(ESTILO6);
        lblUsuario.setForeground(new java.awt.Color(240, 240, 240));
        lblUsuario.setText("Usuario:");
        jPanel2.add(lblUsuario);

        lblNombre.setFont(ESTILO6);
        lblNombre.setForeground(new java.awt.Color(240, 240, 240));
        lblNombre.setText("Usuario:");
        jPanel2.add(lblNombre);

        lblRol.setFont(ESTILO6);
        lblRol.setForeground(new java.awt.Color(240, 240, 240));
        lblRol.setText("Usuario:");
        jPanel2.add(lblRol);

        lblConexion.setFont(ESTILO6);
        lblConexion.setForeground(new java.awt.Color(240, 240, 240));
        lblConexion.setText("Usuario:");
        jPanel2.add(lblConexion);

        jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        pnlBienvenida.add(jPanel1, new java.awt.GridBagConstraints());

        tabPrincipal.addTab("", pnlBienvenida);

        pnlPrincipal.add(tabPrincipal, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnConsulta.setFont(ESTILO4);
        btnConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Find/Find_24x24.png"))); // NOI18N
        btnConsulta.setText("   Consultas   ");
        btnConsulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnConsulta.setFocusable(false);
        btnConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsulta);

        btnEjemplar.setFont(ESTILO4);
        btnEjemplar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/library.png"))); // NOI18N
        btnEjemplar.setText("  Ejemplares en biblioteca  ");
        btnEjemplar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEjemplar.setFocusable(false);
        btnEjemplar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEjemplar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjemplarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEjemplar);

        btnPrestamo.setFont(ESTILO4);
        btnPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Properties/Properties_24x24.png"))); // NOI18N
        btnPrestamo.setText("   Préstamos y devoluciones   ");
        btnPrestamo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPrestamo.setFocusable(false);
        btnPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrestamo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrestamo);

        pnlPrincipal.add(jToolBar1, java.awt.BorderLayout.NORTH);

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Inicio");
        jMenu1.setFont(ESTILO4);

        jMenuItem6.setFont(ESTILO4);
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Log Out/Log Out_16x16.png"))); // NOI18N
        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Biblioteca");
        jMenu4.setFont(ESTILO4);

        mnuRegistroLibro.setFont(ESTILO4);
        mnuRegistroLibro.setText("Registro de libros");
        mnuRegistroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroLibroActionPerformed(evt);
            }
        });
        jMenu4.add(mnuRegistroLibro);

        mnuRegistroEjemplar.setFont(ESTILO4);
        mnuRegistroEjemplar.setText("Registro de ejemplares");
        jMenu4.add(mnuRegistroEjemplar);

        mnuConsultas.setFont(ESTILO4);
        mnuConsultas.setText("Consultas");
        mnuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultasActionPerformed(evt);
            }
        });
        jMenu4.add(mnuConsultas);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Datos de material bibliográfico");
        jMenu5.setFont(ESTILO4);

        mnuRegistroAutor.setFont(ESTILO4);
        mnuRegistroAutor.setText("Registro de autores");
        mnuRegistroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroAutorActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRegistroAutor);

        mnuRegistroEditorial.setFont(ESTILO4);
        mnuRegistroEditorial.setText("Registro de editoriales");
        mnuRegistroEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroEditorialActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRegistroEditorial);

        mnuRegistroMateria.setFont(ESTILO4);
        mnuRegistroMateria.setText("Registro de materias y secciones");
        mnuRegistroMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroMateriaActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRegistroMateria);

        mnuRegistroTema.setFont(ESTILO4);
        mnuRegistroTema.setText("Registro de temas y subtemas");
        mnuRegistroTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroTemaActionPerformed(evt);
            }
        });
        jMenu5.add(mnuRegistroTema);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Préstamos");
        jMenu7.setFont(ESTILO4);

        mnuPersona.setFont(ESTILO4);
        mnuPersona.setText("Información y registro de personas");
        mnuPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPersonaActionPerformed(evt);
            }
        });
        jMenu7.add(mnuPersona);

        mnuPrestamo.setFont(ESTILO4);
        mnuPrestamo.setText("Préstamos y devoluciones");
        mnuPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrestamoActionPerformed(evt);
            }
        });
        jMenu7.add(mnuPrestamo);

        jMenuBar1.add(jMenu7);

        jMenu2.setText("Reportes");
        jMenu2.setFont(ESTILO4);

        mnuReporteEjemplar.setFont(ESTILO4);
        mnuReporteEjemplar.setText("Reporte de ejemplares");
        mnuReporteEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteEjemplarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReporteEjemplar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Configuración");

        mnuUsuario.setText("Control de usuarios");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(mnuUsuario);

        jMenuItem1.setText("Cambiar password");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Préstamos y devoluciones", PrestamoView.getInstance());
    }//GEN-LAST:event_btnPrestamoActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Consultas", ConsultaView.getInstance());
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjemplarActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Ejemplares", EjemplarView.getInstance());
    }//GEN-LAST:event_btnEjemplarActionPerformed

    private void mnuReporteEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteEjemplarActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Reporte de ejemplares", ReporteEjemplarView.getInstance());
    }//GEN-LAST:event_mnuReporteEjemplarActionPerformed

    private void mnuRegistroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroLibroActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Registro de libros", LibroView.getInstance());
    }//GEN-LAST:event_mnuRegistroLibroActionPerformed

    private void mnuRegistroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroAutorActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Registro de autores", AutorView.getInstance());
    }//GEN-LAST:event_mnuRegistroAutorActionPerformed

    private void mnuPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPersonaActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Registro de personas", PersonaView.getInstance());
    }//GEN-LAST:event_mnuPersonaActionPerformed

    private void mnuPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrestamoActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Préstamos y devoluciones", PrestamoView.getInstance());
    }//GEN-LAST:event_mnuPrestamoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mnuRegistroEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroEditorialActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Registro de editoriales", EditorialView.getInstance());
    }//GEN-LAST:event_mnuRegistroEditorialActionPerformed

    private void mnuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultasActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Consultas", ConsultaView.getInstance());
    }//GEN-LAST:event_mnuConsultasActionPerformed

    private void mnuRegistroMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroMateriaActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Materias y secciones", MateriaSeccionView.getInstance());
    }//GEN-LAST:event_mnuRegistroMateriaActionPerformed

    private void mnuRegistroTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroTemaActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Temas y subtemas", TemaView.getInstance());
    }//GEN-LAST:event_mnuRegistroTemaActionPerformed

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        // TODO add your handling code here:
        agregarPestaña("Control de usuarios",UsuarioView.getInstance(),GestorAcceso.permisos("Usuario"));
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btnConsulta;
    private static javax.swing.JButton btnEjemplar;
    private static javax.swing.JButton btnPrestamo;
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JMenu jMenu1;
    private static javax.swing.JMenu jMenu2;
    private static javax.swing.JMenu jMenu3;
    private static javax.swing.JMenu jMenu4;
    private static javax.swing.JMenu jMenu5;
    private static javax.swing.JMenu jMenu7;
    private static javax.swing.JMenuBar jMenuBar1;
    private static javax.swing.JMenuItem jMenuItem1;
    private static javax.swing.JMenuItem jMenuItem6;
    private static javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel jPanel2;
    private static javax.swing.JPanel jPanel3;
    private static javax.swing.JToolBar jToolBar1;
    private static javax.swing.JLabel lblConexion;
    private static javax.swing.JLabel lblNombre;
    private static javax.swing.JLabel lblRol;
    private static javax.swing.JLabel lblUsuario;
    private static javax.swing.JMenuItem mnuConsultas;
    private static javax.swing.JMenuItem mnuPersona;
    private static javax.swing.JMenuItem mnuPrestamo;
    private static javax.swing.JMenuItem mnuRegistroAutor;
    private static javax.swing.JMenuItem mnuRegistroEditorial;
    private static javax.swing.JMenuItem mnuRegistroEjemplar;
    private static javax.swing.JMenuItem mnuRegistroLibro;
    private static javax.swing.JMenuItem mnuRegistroMateria;
    private static javax.swing.JMenuItem mnuRegistroTema;
    private static javax.swing.JMenuItem mnuReporteEjemplar;
    private static javax.swing.JMenuItem mnuUsuario;
    private static javax.swing.JPanel pnlBienvenida;
    private static javax.swing.JPanel pnlPrincipal;
    private static javax.swing.JTabbedPane tabPrincipal;
    // End of variables declaration//GEN-END:variables

    private void iniciarTab(int numero) {
//        for(int i = 0; i <= numero; i++){
//        ButtonTabComponent tab = new ButtonTabComponent(tabPrincipal);
//        tabPrincipal.add("Mantenimiento de inf. de libros", new LibroView());
//        tabPrincipal.setTabComponentAt(0, tab);
//        ButtonTabComponent tab2 = new ButtonTabComponent(tabPrincipal);
//        tabPrincipal.add("Préstamos y devoluciones", new PrestamoView());
//        tabPrincipal.setTabComponentAt(0, tab2);
//        }
    }

    public static void agregarPestaña(String titulo, Component ventana) {
        int index = tabPrincipal.indexOfComponent(ventana);
        if (index >= 0) {
            tabPrincipal.setSelectedIndex(index);
        } else {
            ButtonTabComponent tab = new ButtonTabComponent(tabPrincipal);
            tabPrincipal.add(titulo, ventana);
            tabPrincipal.setTabComponentAt(tabPrincipal.getTabCount() - 1, tab);
            tabPrincipal.setSelectedIndex(tabPrincipal.getTabCount() - 1);
            
        }
    }

    public static void agregarPestaña(String titulo, Component ventana , boolean[] crud) {
        int index = tabPrincipal.indexOfComponent(ventana);
        if (index >= 0) {
            tabPrincipal.setSelectedIndex(index);
        } else {
            ButtonTabComponent tab = new ButtonTabComponent(tabPrincipal);
            ((ControlAcceso)ventana).crud(crud[0], crud[1], crud[2], crud[3]);
            tabPrincipal.add(titulo, ventana);
            tabPrincipal.setTabComponentAt(tabPrincipal.getTabCount() - 1, tab);
            tabPrincipal.setSelectedIndex(tabPrincipal.getTabCount() - 1);
            
        }
    }

    private void mostrarInformacion(Usuario usuario) {
        lblUsuario.setVisible(false);
//        lblUsuario.setText(String.format("Usuario: %s", usuario.getLogin()));
        lblRol.setText(String.format("Rol: %s", usuario.getRol().getNombre()));
        if(usuario.getPersona() != null){
            lblNombre.setText(String.format("Nombre: %s", usuario.getPersona().getNombreCompleto()));
        }else{
            lblNombre.setVisible(false);
        }
        if(usuario.getEvento() == null){
            lblConexion.setText(String.format("Última conexión: %s", "PRIMERA CONEXIÓN"));
        }else{
            lblConexion.setText(String.format("Última conexión: %s", FORMATO_TIMESTAMP.format(usuario.getEvento().getFechaHora())));
        }
        
        
    }

    private void guardarInformacionConexion(Usuario usuario) {
        EventoControlador eventoControlador = EventoControlador.getInstance();
        eventoControlador.prepararCrear();
        eventoControlador.getSeleccionado().setDireccionIP("192.168.0.6");
        eventoControlador.getSeleccionado().setDireccionMAC("54:42:49:73:F8:D2");
        eventoControlador.getSeleccionado().setFechaHora(new Date());
        eventoControlador.getSeleccionado().setTipo(Monitor.LOGIN);
        eventoControlador.getSeleccionado().setUsuario(usuario);
        eventoControlador.accion(NUEVO);
    }

    private void initComponents2() {
        //Para autor
//        System.out.println(USUARIO_ACCESO.get("Autor"));
        mnuRegistroAutor.setEnabled(USUARIO_ACCESO.get("Autor") != 0);
        mnuRegistroEditorial.setEnabled(USUARIO_ACCESO.get("Editorial") != 0);
        mnuRegistroEjemplar.setEnabled(USUARIO_ACCESO.get("Ejemplar") != 0);
        mnuRegistroLibro.setEnabled(USUARIO_ACCESO.get("Libro") != 0);
        mnuRegistroMateria.setEnabled(USUARIO_ACCESO.get("MateriaSeccion") != 0);
        mnuRegistroTema.setEnabled(USUARIO_ACCESO.get("Tema") != 0);
        mnuConsultas.setEnabled(USUARIO_ACCESO.get("Consulta") != 0);
        mnuPrestamo.setEnabled(USUARIO_ACCESO.get("Prestamo") != 0);
        mnuPersona.setEnabled(USUARIO_ACCESO.get("Persona") != 0);
        mnuReporteEjemplar.setEnabled(USUARIO_ACCESO.get("LibroPrestamo") != 0);
        mnuUsuario.setEnabled(USUARIO_ACCESO.get("Usuario") != 0);
        
        btnConsulta.setEnabled(USUARIO_ACCESO.get("Consulta") != 0);
        btnEjemplar.setEnabled(USUARIO_ACCESO.get("Ejemplar") != 0);
        btnPrestamo.setEnabled(USUARIO_ACCESO.get("Prestamo") != 0);
    }
}
