/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.sgb.vistas;

import static com.biosis.sgb.Application.ESTILO1;
import static com.biosis.sgb.Application.ESTILO2;
import static com.biosis.sgb.Application.ESTILO5;
import static com.biosis.sgb.Application.IMG_LOGO_REPORTE;
import static com.biosis.sgb.Application.REPORTE_EJEMPLAR;
import static com.biosis.sgb.Application.REPORTE_INSTITUCION;
import static com.biosis.sgb.Application.REPORTE_LIBRO_USO;
import static com.biosis.sgb.Application.REPORTE_RUC;
import com.biosis.sgb.controlador.EjemplarControlador;
import com.biosis.sgb.controlador.PrestamoControlador;
import com.biosis.sgb.controlador.reportes.LibroPrestamoControlador;
import com.biosis.sgb.entidades.Autor;
import com.biosis.sgb.entidades.Editorial;
import com.biosis.sgb.entidades.Ejemplar;
import com.biosis.sgb.entidades.Seccion;
import com.biosis.sgb.entidades.Tema;
import com.biosis.sgb.entidades.reporte.LibroPrestamo;
import com.biosis.sgb.util.ButtonTabComponent;
import com.biosis.sgb.vistas.dialogos.AutorSelect;
import com.biosis.sgb.vistas.dialogos.EditorialSelect;
import com.biosis.sgb.vistas.dialogos.SeccionSelect;
import com.biosis.sgb.vistas.dialogos.TemaSelect;
import com.personal.utiles.FormularioUtil;
import com.personal.utiles.ReporteUtil;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.SwingWorker;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author Francis
 */
public class ReporteEjemplarView extends javax.swing.JPanel {

    private final EjemplarControlador ejemplarControlador;
    private final LibroPrestamoControlador libroPrestamoControlador;
    private final PrestamoControlador prestamoControlador;

    private Autor autorSeleccionado;
    private Editorial editorialSeleccionada;
    private Seccion seccionSeleccionada;
    private Tema temaSeleccionado;
    /*
    Controles de navegacion
     */
    private int paginaActual = 1;
    private int totalPaginas = 0;
    private int tamanioPagina = 0;

    private List<Ejemplar> ejemplarList;

    private final ReporteUtil reporteUtil;

    public static ReporteEjemplarView instance;

    public static ReporteEjemplarView getInstance() {
        if (instance == null) {
            instance = new ReporteEjemplarView();
        }
        return instance;
    }

    private ReporteEjemplarView() {
        this.reporteUtil = new ReporteUtil();
        libroPrestamoControlador = LibroPrestamoControlador.getInstance();
        prestamoControlador = PrestamoControlador.getInstance();
        initComponents();
        initComponents2();
        this.ejemplarControlador = EjemplarControlador.getInstance();
//        Busqueda busquedaLibro = new Busqueda();
//        busquedaLibro.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupoOpcionesBusqueda = new javax.swing.ButtonGroup();
        grupoUtilizados = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlBusqueda = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        lblEspere = new org.jdesktop.swingx.JXBusyLabel();
        chkAutor = new javax.swing.JCheckBox();
        chkEditorial = new javax.swing.JCheckBox();
        chkSeccion = new javax.swing.JCheckBox();
        chkTema = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        txtSeccion = new javax.swing.JTextField();
        btnSeccion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtTema = new javax.swing.JTextField();
        btnTema = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtEditorial = new javax.swing.JTextField();
        btnEditorial = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtAutor = new javax.swing.JTextField();
        btnAutor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        chkSoloDisponibles = new javax.swing.JCheckBox();
        chkMasUtilizados = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        rad10 = new javax.swing.JRadioButton();
        rad20 = new javax.swing.JRadioButton();
        rad30 = new javax.swing.JRadioButton();
        rad40 = new javax.swing.JRadioButton();
        rad50 = new javax.swing.JRadioButton();
        pnlListado = new javax.swing.JPanel();
        tabVistaPrevia = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(ESTILO5);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte de ejemplares");
        jLabel1.setOpaque(true);
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        pnlBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parámetros de búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1));
        java.awt.GridBagLayout pnlBusquedaLayout = new java.awt.GridBagLayout();
        pnlBusquedaLayout.columnWidths = new int[] {0, 3, 0};
        pnlBusquedaLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        pnlBusqueda.setLayout(pnlBusquedaLayout);

        txtTitulo.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(txtTitulo, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        btnBuscar.setFont(ESTILO1);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Print/Print_16x16.png"))); // NOI18N
        btnBuscar.setText("Generar vista previa");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar);

        lblEspere.setText("Cargando resultados...");
        lblEspere.setFont(ESTILO1);
        jPanel2.add(lblEspere);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(jPanel2, gridBagConstraints);

        chkAutor.setFont(ESTILO1);
        chkAutor.setText("Autor:");
        chkAutor.setOpaque(false);
        chkAutor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkAutorStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkAutor, gridBagConstraints);

        chkEditorial.setFont(ESTILO1);
        chkEditorial.setText("Editorial:");
        chkEditorial.setOpaque(false);
        chkEditorial.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkEditorialStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkEditorial, gridBagConstraints);

        chkSeccion.setFont(ESTILO1);
        chkSeccion.setText("Sección:");
        chkSeccion.setOpaque(false);
        chkSeccion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkSeccionStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkSeccion, gridBagConstraints);

        chkTema.setFont(ESTILO1);
        chkTema.setText("Tema:");
        chkTema.setOpaque(false);
        chkTema.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkTemaStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkTema, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridBagLayout());

        txtSeccion.setEditable(false);
        txtSeccion.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(txtSeccion, gridBagConstraints);
        txtSeccion.setBorder(null);

        btnSeccion.setBackground(new java.awt.Color(204, 204, 255));
        btnSeccion.setFont(ESTILO1);
        btnSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeccionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(btnSeccion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlBusqueda.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.GridBagLayout());

        txtTema.setEditable(false);
        txtTema.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(txtTema, gridBagConstraints);
        txtSeccion.setBorder(null);

        btnTema.setBackground(new java.awt.Color(204, 204, 255));
        btnTema.setFont(ESTILO1);
        btnTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(btnTema, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlBusqueda.add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.GridBagLayout());

        txtEditorial.setEditable(false);
        txtEditorial.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(txtEditorial, gridBagConstraints);
        txtSeccion.setBorder(null);

        btnEditorial.setBackground(new java.awt.Color(204, 204, 255));
        btnEditorial.setFont(ESTILO1);
        btnEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(btnEditorial, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlBusqueda.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.GridBagLayout());

        txtAutor.setEditable(false);
        txtAutor.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel6.add(txtAutor, gridBagConstraints);
        txtSeccion.setBorder(null);

        btnAutor.setBackground(new java.awt.Color(204, 204, 255));
        btnAutor.setFont(ESTILO1);
        btnAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel6.add(btnAutor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlBusqueda.add(jPanel6, gridBagConstraints);

        jLabel2.setFont(ESTILO1);
        jLabel2.setText("Título / ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(jLabel2, gridBagConstraints);

        chkSoloDisponibles.setFont(ESTILO1);
        chkSoloDisponibles.setText("Mostrar sólo ejemplares disponibles");
        chkSoloDisponibles.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkSoloDisponibles, gridBagConstraints);

        chkMasUtilizados.setFont(ESTILO1);
        chkMasUtilizados.setText("Libros más utilizados:");
        chkMasUtilizados.setOpaque(false);
        chkMasUtilizados.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkMasUtilizadosStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkMasUtilizados, gridBagConstraints);

        jPanel7.setOpaque(false);

        rad10.setFont(ESTILO2);
        rad10.setSelected(true);
        rad10.setText("10");
        rad10.setOpaque(false);
        jPanel7.add(rad10);

        rad20.setFont(ESTILO2);
        rad20.setText("20");
        rad20.setOpaque(false);
        jPanel7.add(rad20);

        rad30.setFont(ESTILO2);
        rad30.setText("30");
        rad30.setOpaque(false);
        jPanel7.add(rad30);

        rad40.setFont(ESTILO2);
        rad40.setText("40");
        rad40.setOpaque(false);
        jPanel7.add(rad40);

        rad50.setFont(ESTILO2);
        rad50.setText("50");
        rad50.setOpaque(false);
        jPanel7.add(rad50);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(jPanel7, gridBagConstraints);

        jPanel1.add(pnlBusqueda, java.awt.BorderLayout.PAGE_START);

        pnlListado.setBackground(new java.awt.Color(255, 255, 255));
        pnlListado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vista previa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1        ));
        pnlListado.setLayout(new java.awt.BorderLayout());
        pnlListado.add(tabVistaPrevia, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnlListado, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Busqueda busquedaLibro = new Busqueda();
        busquedaLibro.execute();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeccionActionPerformed
        // TODO add your handling code here:
        SeccionSelect seccionSelect = new SeccionSelect(this, true);
        seccionSelect.setVisible(true);
        this.seccionSeleccionada = seccionSelect.getSeccion();

        if (this.seccionSeleccionada != null) {
            txtSeccion.setText("  " + this.seccionSeleccionada.getNombre());
        }
    }//GEN-LAST:event_btnSeccionActionPerformed

    private void btnTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemaActionPerformed
        // TODO add your handling code here:
        TemaSelect temaSelect = new TemaSelect(this, true);
        temaSelect.setVisible(true);
        this.temaSeleccionado = temaSelect.getTema();

        if (this.temaSeleccionado != null) {
            txtTema.setText("  " + temaSeleccionado.getNombre());
        }
    }//GEN-LAST:event_btnTemaActionPerformed

    private void btnEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialActionPerformed
        // TODO add your handling code here:
        EditorialSelect editorialSelect = new EditorialSelect(this, true);
        editorialSelect.setVisible(true);
        this.editorialSeleccionada = editorialSelect.getEditorial();
        if (this.editorialSeleccionada != null) {
            txtEditorial.setText("  " + this.editorialSeleccionada.getNombre());
        }
    }//GEN-LAST:event_btnEditorialActionPerformed

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        // TODO add your handling code here:
        AutorSelect autorSelect = new AutorSelect(this, true);
        autorSelect.setVisible(true);
        this.autorSeleccionado = autorSelect.getAutor();
        if (this.autorSeleccionado != null) {
            txtAutor.setText(String.format("  %s, %s", autorSeleccionado.getPaterno(), autorSeleccionado.getNombres()));
        }
    }//GEN-LAST:event_btnAutorActionPerformed

    private void chkAutorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkAutorStateChanged
        // TODO add your handling code here:
        checkboxes();
    }//GEN-LAST:event_chkAutorStateChanged

    private void chkEditorialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkEditorialStateChanged
        // TODO add your handling code here:
        checkboxes();
    }//GEN-LAST:event_chkEditorialStateChanged

    private void chkSeccionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkSeccionStateChanged
        // TODO add your handling code here:
        checkboxes();
    }//GEN-LAST:event_chkSeccionStateChanged

    private void chkTemaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkTemaStateChanged
        // TODO add your handling code here:
        checkboxes();
    }//GEN-LAST:event_chkTemaStateChanged

    private void chkMasUtilizadosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkMasUtilizadosStateChanged
        // TODO add your handling code here:
        checkMasUtilizados();
    }//GEN-LAST:event_chkMasUtilizadosStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditorial;
    private javax.swing.JButton btnSeccion;
    private javax.swing.JButton btnTema;
    private javax.swing.JCheckBox chkAutor;
    private javax.swing.JCheckBox chkEditorial;
    private javax.swing.JCheckBox chkMasUtilizados;
    private javax.swing.JCheckBox chkSeccion;
    private javax.swing.JCheckBox chkSoloDisponibles;
    private javax.swing.JCheckBox chkTema;
    private javax.swing.ButtonGroup grupoOpcionesBusqueda;
    private javax.swing.ButtonGroup grupoUtilizados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private org.jdesktop.swingx.JXBusyLabel lblEspere;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlListado;
    private javax.swing.JRadioButton rad10;
    private javax.swing.JRadioButton rad20;
    private javax.swing.JRadioButton rad30;
    private javax.swing.JRadioButton rad40;
    private javax.swing.JRadioButton rad50;
    private javax.swing.JTabbedPane tabVistaPrevia;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtSeccion;
    private javax.swing.JTextField txtTema;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {

        grupoUtilizados.add(rad10);
        grupoUtilizados.add(rad20);
        grupoUtilizados.add(rad30);
        grupoUtilizados.add(rad40);
        grupoUtilizados.add(rad50);

        lblEspere.setVisible(false);
        this.ejemplarList = ObservableCollections.observableList(new ArrayList<Ejemplar>());
    }

    //cambiamos acorde a lo que se requiere
    private void generarReporte() {
//        String busqueda = txtBusqueda.getText();
//        tamanioPagina = Integer.parseInt(cboTamanio.getSelectedItem().toString());

        //AQUI LO PASAMOS A UN SWING WORKER
        if (chkMasUtilizados.isSelected()) {
            List<LibroPrestamo> reporteList = libroPrestamoControlador.consultaMultiple(
                    chkAutor.isSelected() ? autorSeleccionado : null,
                    chkEditorial.isSelected() ? editorialSeleccionada : null,
                    chkSeccion.isSelected() ? seccionSeleccionada : null,
                    chkTema.isSelected() ? temaSeleccionado : null,
                    txtTitulo.getText().trim().toUpperCase(),
                    chkSoloDisponibles.isSelected(),obtenerMaximo());
            
            Map<String, Object> param = new HashMap();
            param.put("reporte_logo", IMG_LOGO_REPORTE.getAbsolutePath());
            param.put("reporte_ruc", REPORTE_RUC);
            param.put("reporte_institucion", REPORTE_INSTITUCION);
            Component reporteComponente = reporteUtil.obtenerReporte(reporteList, REPORTE_LIBRO_USO, param);

            agregarPestaña("Vista previa " + tabVistaPrevia.getTabCount() + 1, reporteComponente);
        } else {
            List<Ejemplar> reporteList = ejemplarControlador.consultaMultiple(
                    chkAutor.isSelected() ? autorSeleccionado : null,
                    chkEditorial.isSelected() ? editorialSeleccionada : null,
                    chkSeccion.isSelected() ? seccionSeleccionada : null,
                    chkTema.isSelected() ? temaSeleccionado : null,
                    txtTitulo.getText().trim().toUpperCase(),
                    chkSoloDisponibles.isSelected());
            Map<String, Object> param = new HashMap();
            param.put("reporte_logo", IMG_LOGO_REPORTE.getAbsolutePath());
            param.put("reporte_ruc", REPORTE_RUC);
            param.put("reporte_institucion", REPORTE_INSTITUCION);
            Component reporteComponente = reporteUtil.obtenerReporte(reporteList, REPORTE_EJEMPLAR, param);

            agregarPestaña("Vista previa " + (tabVistaPrevia.getTabCount() + 1), reporteComponente);
        }
//        ejemplarList.clear();

//        ejemplarList.addAll(this.listar(paginaActual, tamanioPagina));
//        tblEjemplarList.packAll();
    }
    
    private int obtenerMaximo(){
        if(rad10.isSelected()){
            return 10;
        }
        if(rad20.isSelected()){
            return 20;
        }
        if(rad30.isSelected()){
            return 30;
        }
        if(rad40.isSelected()){
            return 40;
        }
        if(rad50.isSelected()){
            return 50;
        }
        return -1;
    }

    private void controles(boolean busqueda) {
        FormularioUtil.activarComponente(pnlBusqueda, !busqueda);
        if (!busqueda) {
            checkboxes();
        }
    }

    private List<Ejemplar> listar(int pagina, int tamanio) {
        int total = 0;
        String txtPatron = txtTitulo.getText();
        total = ejemplarControlador.contarMultiple(
                chkAutor.isSelected() ? autorSeleccionado : null,
                chkEditorial.isSelected() ? editorialSeleccionada : null,
                chkSeccion.isSelected() ? seccionSeleccionada : null,
                chkTema.isSelected() ? temaSeleccionado : null,
                txtPatron.trim().toUpperCase(),
                chkSoloDisponibles.isSelected());

        if (total % tamanio == 0) {
            totalPaginas = total / tamanio;
        } else {
            totalPaginas = (total / tamanio) + 1;
        }

        if (totalPaginas == 0) {
            totalPaginas = 1;
        }

        int desde = (pagina - 1) * tamanio;

        return ejemplarControlador.consultaMultiple(
                chkAutor.isSelected() ? autorSeleccionado : null,
                chkEditorial.isSelected() ? editorialSeleccionada : null,
                chkSeccion.isSelected() ? seccionSeleccionada : null,
                chkTema.isSelected() ? temaSeleccionado : null,
                txtPatron.trim().toUpperCase(),
                chkSoloDisponibles.isSelected(),
                desde, tamanio);
    }

    private void checkboxes() {
        txtAutor.setEditable(false);
        txtEditorial.setEditable(false);
        txtSeccion.setEditable(false);
        txtTema.setEditable(false);

        btnAutor.setEnabled(chkAutor.isSelected());
        btnEditorial.setEnabled(chkEditorial.isSelected());
        btnSeccion.setEnabled(chkSeccion.isSelected());
        btnTema.setEnabled(chkTema.isSelected());
    }

    private void checkMasUtilizados() {
        rad10.setEnabled(chkMasUtilizados.isSelected());
        rad20.setEnabled(chkMasUtilizados.isSelected());
        rad30.setEnabled(chkMasUtilizados.isSelected());
        rad40.setEnabled(chkMasUtilizados.isSelected());
        rad50.setEnabled(chkMasUtilizados.isSelected());
    }

    private void agregarPestaña(String titulo, Component ventana) {
        int index = tabVistaPrevia.indexOfComponent(ventana);
        if (index >= 0) {
            tabVistaPrevia.setSelectedIndex(index);
        } else {
            ButtonTabComponent tab = new ButtonTabComponent(tabVistaPrevia);
            tabVistaPrevia.add(titulo, ventana);
            tabVistaPrevia.setTabComponentAt(tabVistaPrevia.getTabCount() - 1, tab);
            tabVistaPrevia.setSelectedIndex(tabVistaPrevia.getTabCount() - 1);
        }
    }

    private class Busqueda extends SwingWorker<Double, Void> {

        @Override
        protected Double doInBackground() throws Exception {
            controles(true);
            lblEspere.setEnabled(true);
            lblEspere.setVisible(true);
            lblEspere.setBusy(true);
            paginaActual = 1;
            generarReporte();
            return 0.0;
        }

        @Override
        protected void done() {

            lblEspere.setBusy(false);
            lblEspere.setVisible(false);
            controles(false);
        }

    }
}
