/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.sgb.vistas.dialogos;

import static com.biosis.sgb.Application.ESTILO1;
import static com.biosis.sgb.Application.ESTILO2;
import static com.biosis.sgb.Application.ESTILO5;
import static com.biosis.sgb.Application.ESTILO6;
import static com.biosis.sgb.controlador.Controlador.ELIMINAR;
import static com.biosis.sgb.controlador.Controlador.LEER;
import static com.biosis.sgb.controlador.Controlador.MODIFICAR;
import static com.biosis.sgb.controlador.Controlador.NUEVO;
import com.biosis.sgb.controlador.EjemplarControlador;
import com.biosis.sgb.controlador.PrestamoControlador;
import com.biosis.sgb.entidades.Autor;
import com.biosis.sgb.entidades.Ejemplar;
import com.biosis.sgb.entidades.Libro;
import com.biosis.sgb.entidades.Persona;
import com.biosis.sgb.entidades.Prestamo;
import com.personal.utiles.FormularioUtil;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Francis
 */
public class DevolucionDialog extends javax.swing.JDialog {

    /**
     * Creates new form AutorCRUD
     */
    private PrestamoControlador prestamoControlador;
    private int accion;
    private boolean accionRealizada = false;
    private Prestamo prestamo;

    public Prestamo getPrestamo() {
        return prestamo;
    }

    public boolean isAccionRealizada() {
        return accionRealizada;
    }

    public DevolucionDialog(java.awt.Frame parent, boolean modal, int accion, Autor autor) {
        super(parent, modal);
        initComponents();
        initComponents2();
    }

    public DevolucionDialog(Component component, boolean modal, int accion, Prestamo prestamo) {
        super(JOptionPane.getFrameForComponent(component), modal);
        initComponents();
        initComponents2();
        this.prestamo = prestamo;
        this.accion = accion;
        inicializar(prestamo, accion);
        this.setLocationRelativeTo(component);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblTituloVentana = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlPersona = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtPersona = new javax.swing.JTextField();
        pnlEjemplar = new javax.swing.JPanel();
        pnlPersona1 = new javax.swing.JPanel();
        pnlDatosLibro = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        lblSeccion = new javax.swing.JLabel();
        lblAutores = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dcFechaFin = new com.toedter.calendar.JDateChooser();
        pnlDevolucion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dcFechaEntrega = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblTituloVentana.setBackground(new java.awt.Color(204, 204, 255));
        lblTituloVentana.setFont(ESTILO5);
        lblTituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloVentana.setText("Registrar nuevo autor");
        lblTituloVentana.setOpaque(true);
        jPanel1.add(lblTituloVentana, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        pnlPersona.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1));
        java.awt.GridBagLayout pnlPersonaLayout = new java.awt.GridBagLayout();
        pnlPersonaLayout.columnWidths = new int[] {0, 3, 0};
        pnlPersonaLayout.rowHeights = new int[] {0, 5, 0};
        pnlPersona.setLayout(pnlPersonaLayout);

        jLabel1.setFont(ESTILO1);
        jLabel1.setText("Apellidos y nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlPersona.add(jLabel1, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        txtPersona.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(txtPersona, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlPersona.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(pnlPersona, gridBagConstraints);

        pnlEjemplar.setLayout(new java.awt.GridBagLayout());

        pnlPersona1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de ejemplar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1));
        java.awt.GridBagLayout pnlPersona1Layout = new java.awt.GridBagLayout();
        pnlPersona1Layout.columnWidths = new int[] {0, 3, 0, 3, 0};
        pnlPersona1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        pnlPersona1.setLayout(pnlPersona1Layout);

        pnlDatosLibro.setLayout(new java.awt.GridLayout(0, 1, 0, 3));

        lblCodigo.setFont(ESTILO1);
        lblCodigo.setText("Código ejemplar:");
        pnlDatosLibro.add(lblCodigo);

        lblTitulo.setFont(ESTILO1);
        lblTitulo.setText("Titulo:");
        pnlDatosLibro.add(lblTitulo);

        lblEdicion.setFont(ESTILO1);
        lblEdicion.setText("Edición:");
        pnlDatosLibro.add(lblEdicion);

        lblMateria.setFont(ESTILO1);
        lblMateria.setText("Materia:");
        pnlDatosLibro.add(lblMateria);

        lblSeccion.setFont(ESTILO1);
        lblSeccion.setText("Sección:");
        pnlDatosLibro.add(lblSeccion);

        lblAutores.setFont(ESTILO1);
        lblAutores.setText("Autor(es):");
        pnlDatosLibro.add(lblAutores);

        lblEditorial.setFont(ESTILO1);
        lblEditorial.setText("Editorial:");
        pnlDatosLibro.add(lblEditorial);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlPersona1.add(pnlDatosLibro, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlEjemplar.add(pnlPersona1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(pnlEjemplar, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de préstamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jLabel4.setFont(ESTILO1);
        jLabel4.setText("Fecha de préstamo: ");
        jPanel5.add(jLabel4);
        jPanel5.add(dcFechaInicio);

        jLabel3.setFont(ESTILO1);
        jLabel3.setText("  Fecha de devolución: ");
        jPanel5.add(jLabel3);
        jPanel5.add(dcFechaFin);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jPanel5, gridBagConstraints);

        pnlDevolucion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de devolución", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1));
        java.awt.GridBagLayout pnlDevolucionLayout = new java.awt.GridBagLayout();
        pnlDevolucionLayout.columnWidths = new int[] {0, 3, 0};
        pnlDevolucionLayout.rowHeights = new int[] {0, 5, 0};
        pnlDevolucion.setLayout(pnlDevolucionLayout);

        jLabel5.setFont(ESTILO1);
        jLabel5.setText("Fecha de entrega: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlDevolucion.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        pnlDevolucion.add(dcFechaEntrega, gridBagConstraints);

        jLabel2.setFont(ESTILO1);
        jLabel2.setText("Observaciones:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlDevolucion.add(jLabel2, gridBagConstraints);

        txtObservaciones.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlDevolucion.add(txtObservaciones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(pnlDevolucion, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        btnGuardar.setFont(ESTILO6);
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save/Save_16x16.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar);

        btnEditar.setFont(ESTILO6);
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit/Edit_16x16.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar);

        btnEliminar.setFont(ESTILO6);
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete/Delete_16x16.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar);

        btnCancelar.setFont(ESTILO6);
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cancel/Cancel_16x16.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        volcarData(prestamoControlador.getSeleccionado());

        if (prestamoControlador.accion(accion)) {
            FormularioUtil.mensajeExito(this, accion);
            this.accionRealizada = true;
            this.dispose();

        } else {
            FormularioUtil.mensajeError(this, accion);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.accion = MODIFICAR;
        inicializar(prestamo, accion);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.accion = ELIMINAR;
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar este autor(a)?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (this.prestamoControlador.accion(accion)) {
                FormularioUtil.mensajeExito(this, accion);
                this.prestamo = null;
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dcFechaEntrega;
    private com.toedter.calendar.JDateChooser dcFechaFin;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAutores;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloVentana;
    private javax.swing.JPanel pnlDatosLibro;
    private javax.swing.JPanel pnlDevolucion;
    private javax.swing.JPanel pnlEjemplar;
    private javax.swing.JPanel pnlPersona;
    private javax.swing.JPanel pnlPersona1;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtPersona;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        prestamoControlador = PrestamoControlador.getInstance();

//        ejemplarList = ObservableCollections.observableList(new ArrayList<Ejemplar>());
//
//        BeanProperty codigo = BeanProperty.create("codigo");
//        BeanProperty fechaEntrada = BeanProperty.create("fechaEntrada");
//        BeanProperty estado = BeanProperty.create("estado");
//        BeanProperty disponibleDesde = BeanProperty.create("prestamo.fechaDevolucion");
//        JTableBinding bindeoTabla = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, ejemplarList, tblEjemplar);
//        bindeoTabla.addColumnBinding(codigo).setColumnName("Código").setEditable(false);
//        bindeoTabla.addColumnBinding(fechaEntrada).setColumnName("Fecha de ingreso").setEditable(false).setColumnClass(Date.class);
//        bindeoTabla.addColumnBinding(estado).setColumnName("Disponible").setEditable(false);
//        bindeoTabla.addColumnBinding(disponibleDesde).setColumnName("Disponibilidad desde").setEditable(false).setColumnClass(Date.class);
//        bindeoTabla.bind();
//
//        tblEjemplar.setDefaultRenderer(Date.class, new DefaultTableCellRenderer() {
//            final DateFormat dfFecha = new SimpleDateFormat("dd/MM/yyyy");
//
//            @Override
//            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
//                String fecha = "";
//                if (value != null) {
//                    Date date = (Date) value;
//                    fecha = dfFecha.format(date);
//                }
//                return super.getTableCellRendererComponent(table, fecha, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
//            }
//
//        });
//
//        tblEjemplar.getColumn(2).setCellRenderer(new DefaultTableCellRenderer() {
//            @Override
//            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
//                String disponible = "";
//                if (value != null) {
//                    int estado = Integer.parseInt(value.toString());
//                    if (estado == 0) {
//                        disponible = "NO";
//                    } else {
//                        disponible = "SI";
//                    }
//                }
//                return super.getTableCellRendererComponent(table, disponible, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
//            }
//
//        });
    }

    private void volcarData(Prestamo seleccionado) {
        seleccionado.setFechaEntrega(dcFechaEntrega.getDate());
        seleccionado.setObservaciones(txtObservaciones.getText());

        if (this.accion == NUEVO) {
            seleccionado.setFechaHoraCreacion(new Date());

        }
    }

    private void inicializar(Prestamo prestamo, int accion) {
        switch (accion) {
            case NUEVO:

                lblTituloVentana.setText("Registrar préstamo");
                btnCancelar.setText("Cancelar");
                break;
            case MODIFICAR:
                lblTituloVentana.setText("Registrar devolución");
                btnCancelar.setText("Cancelar");
                break;
            case LEER:
                lblTituloVentana.setText("Ver inf. de préstamo");
                btnCancelar.setText("Cerrar");
                break;
        }

        prestamoControlador.setSeleccionado(prestamo);

        inicializarControles(accion);
        if (accion == MODIFICAR || accion == LEER) {
            llenarCampos(prestamo);
        }

    }

    private void llenarCampos(Prestamo prestamo) {
        txtPersona.setText(prestamo.getPersona().getNombreCompleto());
        mostrarDatosLibro(prestamo.getEjemplar().getLibro());
        lblCodigo.setText("Código de ejemplar: "+prestamo.getEjemplar().getCodigo());
        dcFechaInicio.setDate(prestamo.getFechaPrestamo());
        dcFechaFin.setDate(prestamo.getFechaDevolucion());
    }

    private void inicializarControles(int accion) {
        boolean leer = accion == LEER;
        boolean leerModificar = accion == LEER || accion == MODIFICAR;
        boolean nuevoModificar = accion == NUEVO || accion == MODIFICAR;
        boolean modificar = accion == MODIFICAR;

        this.btnEditar.setVisible(accion == LEER);
        this.btnEliminar.setVisible(leerModificar);
        this.btnGuardar.setVisible(nuevoModificar);
        txtPersona.setEditable(false);
        FormularioUtil.activarComponente(dcFechaInicio, !modificar);
        FormularioUtil.activarComponente(dcFechaFin, !modificar);
        FormularioUtil.activarComponente(dcFechaEntrega, modificar);
//        this.lblCodigo.setVisible(false);

    }

    private void mostrarDatosLibro(Libro libro) {
        lblTitulo.setText(String.format("Título: %s", libro.getTitulo()));
        lblEdicion.setText(String.format("Edición: %s", libro.getNumeroEdicion()));
        lblMateria.setText(String.format("Materia: %s", libro.getSeccion().getMateria().getNombre()));
        lblSeccion.setText(String.format("Sección: %s", libro.getSeccion().getNombre()));
        lblAutores.setText(String.format("Autor(es): %s", libro.getAutoresNombre()));
        lblEditorial.setText(String.format("Editorial: %s", libro.getEditorial().getNombre()));
    }
}
