/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.sgb.vistas.dialogos;

import static com.biosis.sgb.Application.ESTILO1;
import static com.biosis.sgb.Application.ESTILO2;
import static com.biosis.sgb.Application.ESTILO5;
import static com.biosis.sgb.Application.ESTILO6;
import static com.biosis.sgb.controlador.Controlador.ELIMINAR;
import static com.biosis.sgb.controlador.Controlador.LEER;
import static com.biosis.sgb.controlador.Controlador.MODIFICAR;
import static com.biosis.sgb.controlador.Controlador.NUEVO;
import com.biosis.sgb.controlador.EjemplarControlador;
import com.biosis.sgb.controlador.PrestamoControlador;
import com.biosis.sgb.controlador.ProcedenciaControlador;
import com.biosis.sgb.entidades.Autor;
import com.biosis.sgb.entidades.Ejemplar;
import com.biosis.sgb.entidades.Libro;
import com.biosis.sgb.entidades.Persona;
import com.biosis.sgb.entidades.Prestamo;
import com.biosis.sgb.entidades.Procedencia;
import com.biosis.sgb.util.AbstractListCellRenderer;
import com.personal.utiles.FormularioUtil;
import java.awt.Component;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Francis
 */
public class EjemplarCRUD extends javax.swing.JDialog {

    /**
     * Creates new form AutorCRUD
     */
    private EjemplarControlador ejemplarControlador;
    private ProcedenciaControlador procedenciaControlador;

    private int accion;
    private boolean accionRealizada = false;
    private Ejemplar ejemplar;
    private List<Procedencia> procedenciaList;

    private Libro libroSeleccionado;

    public Ejemplar getEjemplar() {
        return ejemplar;
    }

    public boolean isAccionRealizada() {
        return accionRealizada;
    }

    public EjemplarCRUD(java.awt.Frame parent, boolean modal, int accion, Autor autor) {
        super(parent, modal);
        initComponents();
        initComponents2();
    }

    public EjemplarCRUD(Component component, boolean modal, int accion, Ejemplar ejemplar) {
        super(JOptionPane.getFrameForComponent(component), modal);
        initComponents();
        initComponents2();
        this.ejemplar = ejemplar;
        this.accion = accion;
        inicializar(ejemplar, accion);
        this.setLocationRelativeTo(component);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblTituloVentana = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlEjemplar = new javax.swing.JPanel();
        pnlPersona1 = new javax.swing.JPanel();
        lblBusqueda = new javax.swing.JLabel();
        pnlBusquedaLibro = new javax.swing.JPanel();
        txtLibro = new javax.swing.JTextField();
        btnLibro = new javax.swing.JButton();
        pnlEjemplaresDisponibles = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblEdicion1 = new javax.swing.JLabel();
        lblMateria1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        dcFechaEntrada = new com.toedter.calendar.JDateChooser();
        cboProcedencia = new javax.swing.JComboBox<>();
        pnlDatosLibro = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        lblSeccion = new javax.swing.JLabel();
        lblAutores = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblTituloVentana.setBackground(new java.awt.Color(204, 204, 255));
        lblTituloVentana.setFont(ESTILO5);
        lblTituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloVentana.setText("Registrar nuevo autor");
        lblTituloVentana.setOpaque(true);
        jPanel1.add(lblTituloVentana, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 3, 0, 3, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        pnlEjemplar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlEjemplar.setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagLayout pnlPersona1Layout = new java.awt.GridBagLayout();
        pnlPersona1Layout.columnWidths = new int[] {0, 3, 0, 3, 0};
        pnlPersona1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        pnlPersona1.setLayout(pnlPersona1Layout);

        lblBusqueda.setFont(ESTILO1);
        lblBusqueda.setText("Búsqueda de libro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlPersona1.add(lblBusqueda, gridBagConstraints);

        pnlBusquedaLibro.setLayout(new java.awt.GridBagLayout());

        txtLibro.setFont(ESTILO2);
        txtLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLibroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlBusquedaLibro.add(txtLibro, gridBagConstraints);

        btnLibro.setFont(ESTILO1);
        btnLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        pnlBusquedaLibro.add(btnLibro, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlPersona1.add(pnlBusquedaLibro, gridBagConstraints);

        pnlEjemplaresDisponibles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de ejemplar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1));
        java.awt.GridBagLayout pnlEjemplaresDisponiblesLayout = new java.awt.GridBagLayout();
        pnlEjemplaresDisponiblesLayout.columnWidths = new int[] {0, 3, 0};
        pnlEjemplaresDisponiblesLayout.rowHeights = new int[] {0, 5, 0, 5, 0};
        pnlEjemplaresDisponibles.setLayout(pnlEjemplaresDisponiblesLayout);

        lblTitulo1.setFont(ESTILO1);
        lblTitulo1.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEjemplaresDisponibles.add(lblTitulo1, gridBagConstraints);

        lblEdicion1.setFont(ESTILO1);
        lblEdicion1.setText("Fecha de entrada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEjemplaresDisponibles.add(lblEdicion1, gridBagConstraints);

        lblMateria1.setFont(ESTILO1);
        lblMateria1.setText("Procedencia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEjemplaresDisponibles.add(lblMateria1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        pnlEjemplaresDisponibles.add(txtCodigo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEjemplaresDisponibles.add(dcFechaEntrada, gridBagConstraints);

        cboProcedencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEjemplaresDisponibles.add(cboProcedencia, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 10.0;
        pnlPersona1.add(pnlEjemplaresDisponibles, gridBagConstraints);

        pnlDatosLibro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1));
        pnlDatosLibro.setLayout(new java.awt.GridLayout(0, 1, 0, 3));

        lblTitulo.setFont(ESTILO1);
        lblTitulo.setText("Titulo:");
        pnlDatosLibro.add(lblTitulo);

        lblEdicion.setFont(ESTILO1);
        lblEdicion.setText("Edición:");
        pnlDatosLibro.add(lblEdicion);

        lblMateria.setFont(ESTILO1);
        lblMateria.setText("Materia:");
        pnlDatosLibro.add(lblMateria);

        lblSeccion.setFont(ESTILO1);
        lblSeccion.setText("Sección:");
        pnlDatosLibro.add(lblSeccion);

        lblAutores.setFont(ESTILO1);
        lblAutores.setText("Autor(es):");
        pnlDatosLibro.add(lblAutores);

        lblEditorial.setFont(ESTILO1);
        lblEditorial.setText("Editorial:");
        pnlDatosLibro.add(lblEditorial);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlPersona1.add(pnlDatosLibro, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlEjemplar.add(pnlPersona1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(pnlEjemplar, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        btnGuardar.setFont(ESTILO6);
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save/Save_16x16.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar);

        btnEditar.setFont(ESTILO6);
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit/Edit_16x16.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar);

        btnEliminar.setFont(ESTILO6);
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete/Delete_16x16.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar);

        btnCancelar.setFont(ESTILO6);
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cancel/Cancel_16x16.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        volcarData(ejemplarControlador.getSeleccionado());

        if (ejemplarControlador.accion(accion)) {
            FormularioUtil.mensajeExito(this, accion);
            this.accionRealizada = true;
            this.dispose();

        } else {
            FormularioUtil.mensajeError(this, accion);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.accion = MODIFICAR;
        inicializar(ejemplar, accion);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.accion = ELIMINAR;
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar este autor(a)?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (this.ejemplarControlador.accion(accion)) {
                FormularioUtil.mensajeExito(this, accion);
                this.ejemplar = null;
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroActionPerformed
        // TODO add your handling code here:
        LibroSelect libroSelect = new LibroSelect(this, true);
        libroSelect.setVisible(true);
        Libro libro = libroSelect.getLibro();
        if (libro != null) {
            this.libroSeleccionado = libro;
            txtLibro.setText(libro.getTitulo());
            mostrarDatosLibro(libro);
//            ejemplarList.addAll(libro.getEjemplarList());

        }
//        if (personaSeleccionada != null) {
//            txtPersona.setText(String.format("%s %s, %s", personaSeleccionada.getPaterno(), personaSeleccionada.getMaterno(), personaSeleccionada.getNombres()));
//        }
    }//GEN-LAST:event_btnLibroActionPerformed

    private void txtLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLibroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLibro;
    private javax.swing.JComboBox<String> cboProcedencia;
    private com.toedter.calendar.JDateChooser dcFechaEntrada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAutores;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblEdicion1;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblMateria1;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTituloVentana;
    private javax.swing.JPanel pnlBusquedaLibro;
    private javax.swing.JPanel pnlDatosLibro;
    private javax.swing.JPanel pnlEjemplar;
    private javax.swing.JPanel pnlEjemplaresDisponibles;
    private javax.swing.JPanel pnlPersona1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtLibro;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        ejemplarControlador = EjemplarControlador.getInstance();
        procedenciaControlador = ProcedenciaControlador.getInstance();

        procedenciaList = procedenciaControlador.buscarTodos();

        JComboBoxBinding procedenciaBind = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ, procedenciaList, cboProcedencia);
        procedenciaBind.bind();

        cboProcedencia.setRenderer(new AbstractListCellRenderer<Procedencia>() {
            @Override
            public String getTexto(Procedencia value) {
                return value.getNombre();
            }

            @Override
            public ImageIcon getIcono(Procedencia value) {
                return null;
            }
        });
    }

    private void volcarData(Ejemplar seleccionado) {
        seleccionado.setLibro(libroSeleccionado);
        seleccionado.setFechaEntrada(dcFechaEntrada.getDate());
        seleccionado.setCodigo(txtCodigo.getText());
        seleccionado.setProcedencia((Procedencia) cboProcedencia.getSelectedItem());
        if (this.accion == NUEVO) {
            seleccionado.setEstado(1);
            seleccionado.setFechaHoraCreacion(new Date());

        }
    }

    private void inicializar(Ejemplar ejemplar, int accion) {
        switch (accion) {
            case NUEVO:

                lblTituloVentana.setText("Registrar ejemplar");
                btnCancelar.setText("Cancelar");
                break;
            case MODIFICAR:
                lblTituloVentana.setText("Modificar inf. de ejemplar");
                btnCancelar.setText("Cancelar");
                break;
            case LEER:
                lblTituloVentana.setText("Ver inf. de ejemplar");
                btnCancelar.setText("Cerrar");
                break;
        }

        ejemplarControlador.setSeleccionado(ejemplar);

        inicializarControles(accion);
        if (accion == MODIFICAR || accion == LEER) {
            llenarCampos(ejemplar);
        }

    }

    private void llenarCampos(Ejemplar ejemplar) {
        mostrarDatosLibro(ejemplar.getLibro());
        dcFechaEntrada.setDate(ejemplar.getFechaEntrada());
        txtCodigo.setText(ejemplar.getCodigo());
        cboProcedencia.setSelectedItem(ejemplar.getProcedencia());
    }

    private void inicializarControles(int accion) {
        boolean leer = accion == LEER;
        boolean leerModificar = accion == LEER || accion == MODIFICAR;
        boolean nuevoModificar = accion == NUEVO || accion == MODIFICAR;

        this.btnEditar.setVisible(accion == LEER);
        this.btnEliminar.setVisible(leerModificar);
        this.btnGuardar.setVisible(nuevoModificar);
        txtLibro.setEditable(false);
        FormularioUtil.activarComponente(dcFechaEntrada, !leer);

        cboProcedencia.setEnabled(!leer);
        txtCodigo.setEditable(!leer);

    }

    private void mostrarDatosLibro(Libro libro) {
        lblTitulo.setText(String.format("Título: %s", libro.getTitulo()));
        lblEdicion.setText(String.format("Edición: %s", libro.getNumeroEdicion()));
        lblMateria.setText(String.format("Materia: %s", libro.getSeccion().getMateria().getNombre()));
        lblSeccion.setText(String.format("Sección: %s", libro.getSeccion().getNombre()));
        lblAutores.setText(String.format("Autor(es): %s", libro.getAutoresNombre()));
        lblEditorial.setText(String.format("Editorial: %s", libro.getEditorial().getNombre()));
    }
}
