/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.sgb.vistas.dialogos;

import static com.biosis.sgb.Application.ESTILO1;
import static com.biosis.sgb.Application.ESTILO2;
import static com.biosis.sgb.Application.ESTILO5;
import static com.biosis.sgb.controlador.Controlador.ELIMINAR;
import static com.biosis.sgb.controlador.Controlador.LEER;
import static com.biosis.sgb.controlador.Controlador.MODIFICAR;
import static com.biosis.sgb.controlador.Controlador.NUEVO;
import com.biosis.sgb.controlador.EditorialControlador;
import com.biosis.sgb.controlador.EjemplarControlador;
import com.biosis.sgb.controlador.IndiceControlador;
import com.biosis.sgb.controlador.LibroAutorControlador;
import com.biosis.sgb.controlador.LibroControlador;
import com.biosis.sgb.controlador.LibroTemaControlador;
import com.biosis.sgb.controlador.TipoLibroControlador;
import com.biosis.sgb.entidades.Autor;
import com.biosis.sgb.entidades.Editorial;
import com.biosis.sgb.entidades.Ejemplar;
import com.biosis.sgb.entidades.Indice;
import com.biosis.sgb.entidades.Libro;
import com.biosis.sgb.entidades.LibroAutor;
import com.biosis.sgb.entidades.LibroTema;
import com.biosis.sgb.entidades.Seccion;
import com.biosis.sgb.entidades.Tema;
import com.biosis.sgb.entidades.TipoLibro;
import com.biosis.sgb.util.AbstractListCellRenderer;
import com.personal.utiles.FormularioUtil;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JComboBoxBinding;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Francis
 */
public class LibroCRUD extends javax.swing.JDialog {

    /**
     * Creates new form AutorCRUD
     */
    private LibroAutorControlador libroAutorControlador;
    private LibroTemaControlador libroTemaControlador;

    private LibroControlador libroControlador;
    private EditorialControlador editorialControlador;
    private TipoLibroControlador tipoLibroControlador;
    private IndiceControlador indiceControlador;
    private EjemplarControlador ejemplarControlador;

    private int accion;
    private boolean accionRealizada = false;
    private Libro libro;

    private List<Editorial> editorialList;

    private Seccion seccionSeleccionada;

    private List<LibroAutor> libroAutorList;
    private List<LibroTema> libroTemaList;
    private List<Indice> indiceList;
    private List<TipoLibro> tipoLibroList;
    private List<Ejemplar> ejemplarList;

    public Libro getLibro() {
        return libro;
    }

    public boolean isAccionRealizada() {
        return accionRealizada;
    }

    public LibroCRUD(java.awt.Frame parent, boolean modal, int accion, Libro libro) {
        super(parent, modal);
        initComponents();
        initComponents2();
    }

    public LibroCRUD(Component component, boolean modal, int accion, Libro libro) {
        super(JOptionPane.getFrameForComponent(component), modal);
        initComponents();
        initComponents2();
        this.libro = libro;
        this.accion = accion;
        inicializar(libro, accion);
        this.setLocationRelativeTo(component);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tabPrincipal = new javax.swing.JTabbedPane();
        pnlPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtISBN10 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtISBN13 = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        pnlClasificacion1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSeccion = new javax.swing.JTextField();
        btnSeccion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTomo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtVolumen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboEditorial = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEdicion = new javax.swing.JTextField();
        txtNroPaginas = new javax.swing.JTextField();
        tabAutorTemaIndice = new javax.swing.JTabbedPane();
        pnlAutor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutor = new org.jdesktop.swingx.JXTable();
        pnlAutorAccion = new javax.swing.JPanel();
        btnAniadirAutor = new javax.swing.JButton();
        btnQuitarAutor = new javax.swing.JButton();
        pnlTema = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTema = new org.jdesktop.swingx.JXTable();
        pnlTemaAccion = new javax.swing.JPanel();
        btnAniadirTema = new javax.swing.JButton();
        btnQuitarTema = new javax.swing.JButton();
        pnlIndice = new javax.swing.JPanel();
        pnlIndiceAccion = new javax.swing.JPanel();
        btnAniadirIndice = new javax.swing.JButton();
        btnQuitarIndice = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblIndice = new org.jdesktop.swingx.JXTable();
        pnlIndiceOrden = new javax.swing.JPanel();
        btnSubirIndice = new javax.swing.JButton();
        btnBajarIndice = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dcFechaPublicacion = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        cboTipoLibro = new javax.swing.JComboBox<>();
        btnEditorialNuevo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlEjemplar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento Libro");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        tabPrincipal.setOpaque(true);
        tabPrincipal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPrincipalStateChanged(evt);
            }
        });

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        lblTitulo.setBackground(new java.awt.Color(204, 204, 255));
        lblTitulo.setFont(ESTILO5);
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registrar nuevo autor");
        lblTitulo.setOpaque(true);
        pnlPrincipal.add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 3, 0, 3, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel3.setFont(ESTILO1);
        jLabel3.setText("ISBN 13:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel3, gridBagConstraints);

        txtISBN10.setColumns(10);
        txtISBN10.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(txtISBN10, gridBagConstraints);

        jLabel6.setFont(ESTILO1);
        jLabel6.setText("Título:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(ESTILO1);
        jLabel7.setText("ISBN 10:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel7, gridBagConstraints);

        txtISBN13.setColumns(13);
        txtISBN13.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(txtISBN13, gridBagConstraints);

        txtTitulo.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(txtTitulo, gridBagConstraints);

        pnlClasificacion1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clasificación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1));
        pnlClasificacion1.setOpaque(false);
        java.awt.GridBagLayout pnlClasificacion1Layout = new java.awt.GridBagLayout();
        pnlClasificacion1Layout.columnWidths = new int[] {0, 3, 0, 3, 0};
        pnlClasificacion1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        pnlClasificacion1.setLayout(pnlClasificacion1Layout);

        jLabel8.setFont(ESTILO1);
        jLabel8.setText("Sección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlClasificacion1.add(jLabel8, gridBagConstraints);

        txtSeccion.setEditable(false);
        txtSeccion.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlClasificacion1.add(txtSeccion, gridBagConstraints);

        btnSeccion.setFont(ESTILO1);
        btnSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnSeccion.setText("Elegir sección");
        btnSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeccionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        pnlClasificacion1.add(btnSeccion, gridBagConstraints);

        jLabel9.setFont(ESTILO1);
        jLabel9.setText("Número:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlClasificacion1.add(jLabel9, gridBagConstraints);

        txtNumero.setColumns(4);
        txtNumero.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlClasificacion1.add(txtNumero, gridBagConstraints);

        jLabel10.setFont(ESTILO1);
        jLabel10.setText("Volúmen:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlClasificacion1.add(jLabel10, gridBagConstraints);

        txtTomo.setColumns(4);
        txtTomo.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlClasificacion1.add(txtTomo, gridBagConstraints);

        jLabel11.setFont(ESTILO1);
        jLabel11.setText("Tomo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlClasificacion1.add(jLabel11, gridBagConstraints);

        txtVolumen.setColumns(4);
        txtVolumen.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlClasificacion1.add(txtVolumen, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(pnlClasificacion1, gridBagConstraints);

        jLabel1.setFont(ESTILO1);
        jLabel1.setText("Editorial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel1, gridBagConstraints);

        cboEditorial.setFont(ESTILO2);
        cboEditorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(cboEditorial, gridBagConstraints);

        jLabel2.setFont(ESTILO1);
        jLabel2.setText("Edición:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(ESTILO1);
        jLabel4.setText("Fecha de publicación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel4, gridBagConstraints);

        txtEdicion.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(txtEdicion, gridBagConstraints);

        txtNroPaginas.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(txtNroPaginas, gridBagConstraints);

        pnlAutor.setOpaque(false);
        pnlAutor.setLayout(new java.awt.BorderLayout());

        tblAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAutor.setFont(ESTILO2);
        tblAutor.setRowHeight(20);
        jScrollPane1.setViewportView(tblAutor);

        pnlAutor.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlAutorAccion.setOpaque(false);
        pnlAutorAccion.setLayout(new javax.swing.BoxLayout(pnlAutorAccion, javax.swing.BoxLayout.LINE_AXIS));

        btnAniadirAutor.setFont(ESTILO1);
        btnAniadirAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add/Add_16x16.png"))); // NOI18N
        btnAniadirAutor.setText("Añadir autor");
        btnAniadirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirAutorActionPerformed(evt);
            }
        });
        pnlAutorAccion.add(btnAniadirAutor);

        btnQuitarAutor.setFont(ESTILO1);
        btnQuitarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete/Delete_16x16.png"))); // NOI18N
        btnQuitarAutor.setText("Quitar autor");
        btnQuitarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarAutorActionPerformed(evt);
            }
        });
        pnlAutorAccion.add(btnQuitarAutor);

        pnlAutor.add(pnlAutorAccion, java.awt.BorderLayout.PAGE_START);

        tabAutorTemaIndice.addTab("Autor(es)", pnlAutor);

        pnlTema.setLayout(new java.awt.BorderLayout());

        tblTema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTema);

        pnlTema.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlTemaAccion.setOpaque(false);
        pnlTemaAccion.setLayout(new javax.swing.BoxLayout(pnlTemaAccion, javax.swing.BoxLayout.LINE_AXIS));

        btnAniadirTema.setFont(ESTILO1);
        btnAniadirTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add/Add_16x16.png"))); // NOI18N
        btnAniadirTema.setText("Añadir tema");
        btnAniadirTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirTemaActionPerformed(evt);
            }
        });
        pnlTemaAccion.add(btnAniadirTema);

        btnQuitarTema.setFont(ESTILO1);
        btnQuitarTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete/Delete_16x16.png"))); // NOI18N
        btnQuitarTema.setText("Quitar tema");
        btnQuitarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarTemaActionPerformed(evt);
            }
        });
        pnlTemaAccion.add(btnQuitarTema);

        pnlTema.add(pnlTemaAccion, java.awt.BorderLayout.PAGE_START);

        tabAutorTemaIndice.addTab("Tema(s)", pnlTema);

        pnlIndice.setLayout(new java.awt.BorderLayout());

        pnlIndiceAccion.setOpaque(false);
        pnlIndiceAccion.setLayout(new javax.swing.BoxLayout(pnlIndiceAccion, javax.swing.BoxLayout.LINE_AXIS));

        btnAniadirIndice.setFont(ESTILO1);
        btnAniadirIndice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add/Add_16x16.png"))); // NOI18N
        btnAniadirIndice.setText("Añadir");
        btnAniadirIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirIndiceActionPerformed(evt);
            }
        });
        pnlIndiceAccion.add(btnAniadirIndice);

        btnQuitarIndice.setFont(ESTILO1);
        btnQuitarIndice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete/Delete_16x16.png"))); // NOI18N
        btnQuitarIndice.setText("Quitar");
        btnQuitarIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarIndiceActionPerformed(evt);
            }
        });
        pnlIndiceAccion.add(btnQuitarIndice);

        pnlIndice.add(pnlIndiceAccion, java.awt.BorderLayout.PAGE_START);

        tblIndice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblIndice);

        pnlIndice.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pnlIndiceOrden.setLayout(new java.awt.GridLayout(0, 1));

        btnSubirIndice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stock Index Up/Stock Index Up_16x16.png"))); // NOI18N
        btnSubirIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirIndiceActionPerformed(evt);
            }
        });
        pnlIndiceOrden.add(btnSubirIndice);

        btnBajarIndice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stock Index Down/Stock Index Down_16x16.png"))); // NOI18N
        btnBajarIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajarIndiceActionPerformed(evt);
            }
        });
        pnlIndiceOrden.add(btnBajarIndice);

        pnlIndice.add(pnlIndiceOrden, java.awt.BorderLayout.LINE_END);

        tabAutorTemaIndice.addTab("Índice", pnlIndice);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(tabAutorTemaIndice, gridBagConstraints);

        jLabel5.setFont(ESTILO1);
        jLabel5.setText("Nro Páginas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel5, gridBagConstraints);

        dcFechaPublicacion.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(dcFechaPublicacion, gridBagConstraints);

        jLabel12.setFont(ESTILO1);
        jLabel12.setText("Tipo de libro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(jLabel12, gridBagConstraints);

        cboTipoLibro.setFont(ESTILO2);
        cboTipoLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(cboTipoLibro, gridBagConstraints);

        btnEditorialNuevo.setFont(ESTILO1);
        btnEditorialNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add/Add_16x16.png"))); // NOI18N
        btnEditorialNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialNuevoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        jPanel2.add(btnEditorialNuevo, gridBagConstraints);

        pnlPrincipal.add(jPanel2, java.awt.BorderLayout.CENTER);

        btnGuardar.setFont(ESTILO1);
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save/Save_16x16.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar);

        btnEditar.setFont(ESTILO1);
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit/Edit_16x16.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar);

        btnEliminar.setFont(ESTILO1);
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete/Delete_16x16.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar);

        btnCancelar.setFont(ESTILO1);
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cancel/Cancel_16x16.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        pnlPrincipal.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        tabPrincipal.addTab("Datos del libro", pnlPrincipal);

        javax.swing.GroupLayout pnlEjemplarLayout = new javax.swing.GroupLayout(pnlEjemplar);
        pnlEjemplar.setLayout(pnlEjemplarLayout);
        pnlEjemplarLayout.setHorizontalGroup(
            pnlEjemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        pnlEjemplarLayout.setVerticalGroup(
            pnlEjemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        tabPrincipal.addTab("Ver ejemplares", pnlEjemplar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        volcarData(libroControlador.getSeleccionado());

        if (libroControlador.accion(accion)) {
            FormularioUtil.mensajeExito(this, accion);
            this.accionRealizada = true;
            this.dispose();

        } else {
            FormularioUtil.mensajeError(this, accion);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.accion = MODIFICAR;
        inicializar(libro, accion);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.accion = ELIMINAR;
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar este autor(a)?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (this.libroControlador.accion(accion)) {
                FormularioUtil.mensajeExito(this, accion);
                this.libro = null;
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tabPrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPrincipalStateChanged
        // TODO add your handling code here:
        if (this.accion != NUEVO) {
            int index = tabPrincipal.getSelectedIndex();
            if (index == 1) {

            }
        }


    }//GEN-LAST:event_tabPrincipalStateChanged

    private void btnSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeccionActionPerformed
        // TODO add your handling code here:
        SeccionSelect seccionSelect = new SeccionSelect(this, true);
        seccionSelect.setVisible(true);
        if (seccionSelect.getSeccion() != null) {
            setSeccionSeleccionada(seccionSelect.getSeccion());
        }


    }//GEN-LAST:event_btnSeccionActionPerformed

    private void btnAniadirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirAutorActionPerformed
        // TODO add your handling code here:
        AutorSelect autorSelect = new AutorSelect(this, true);
        autorSelect.setVisible(true);
        Autor autor = autorSelect.getAutor();
        if (autor != null) {
            libroAutorControlador.prepararCrear();
            LibroAutor libroAutor = libroAutorControlador.getSeleccionado();
            libroAutor.setAutor(autor);
            libroAutor.setLibro(libro);
            libroAutorList.add(libroAutor);
            libro.getLibroAutorList().add(libroAutor);
        }
    }//GEN-LAST:event_btnAniadirAutorActionPerformed

    private void btnAniadirIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirIndiceActionPerformed
        // TODO add your handling code here:
        String indiceStr = "";
        do {
            indiceStr = JOptionPane.showInputDialog(this, "Ingrese la entrada de índice", "Mensaje del sistema", JOptionPane.INFORMATION_MESSAGE);
        } while (indiceStr.trim().isEmpty());
        indiceControlador.prepararCrear();
        Indice indice = indiceControlador.getSeleccionado();
        indice.setOrden(indiceList.size());
        indice.setLibro(libro);
        indice.setDescripcion(indiceStr);
        indiceList.add(indice);
        libro.getIndiceList().add(indice);
    }//GEN-LAST:event_btnAniadirIndiceActionPerformed

    private void btnQuitarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarAutorActionPerformed
        // TODO add your handling code here:
        int fila = tblAutor.getSelectedRow();
        if (fila != -1) {
            LibroAutor libroAutor = libroAutorList.get(fila);
            libroAutorList.remove(fila);
            libro.getLibroAutorList().remove(libroAutor);
        }
    }//GEN-LAST:event_btnQuitarAutorActionPerformed

    private void btnAniadirTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirTemaActionPerformed
        // TODO add your handling code here:
        TemaSelect temaSelect = new TemaSelect(this, true);
        temaSelect.setVisible(true);
        Tema tema = temaSelect.getTema();
        if (tema != null) {
            libroTemaControlador.prepararCrear();
            LibroTema libroTema = libroTemaControlador.getSeleccionado();
            libroTema.setTema(tema);
            libroTema.setLibro(libro);
            libroTemaList.add(libroTema);
            libro.getLibroTemaList().add(libroTema);
        }
    }//GEN-LAST:event_btnAniadirTemaActionPerformed

    private void btnQuitarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarTemaActionPerformed
        // TODO add your handling code here:
        int fila = tblTema.getSelectedRow();
        if (fila != -1) {
            LibroTema libroTema = libroTemaList.get(fila);
            libroTemaList.remove(fila);
            libro.getLibroTemaList().remove(libroTema);
        }
    }//GEN-LAST:event_btnQuitarTemaActionPerformed

    private void btnQuitarIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarIndiceActionPerformed
        // TODO add your handling code here:
        int fila = tblIndice.getSelectedRow();
        if (fila != -1) {
            Indice indice = indiceList.get(fila);
            indiceList.remove(fila);
            libro.getIndiceList().remove(indice);
        }
    }//GEN-LAST:event_btnQuitarIndiceActionPerformed

    private void btnSubirIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirIndiceActionPerformed
        // TODO add your handling code here:
        int fila = tblIndice.getSelectedRow();
        if (fila > 0) {
            int filaSuperior = fila - 1;
            Indice indice = indiceList.get(fila);
            Indice indiceSuperior = indiceList.get(filaSuperior);
            indice.setOrden(filaSuperior);
            indiceSuperior.setOrden(fila);
            indiceList.set(filaSuperior, indice);
            indiceList.set(fila, indiceSuperior);

//            libro.getIndiceList().get(fila).setOrden(filaSuperior);
//            libro.getIndiceList().get(filaSuperior).setOrden(fila);
            libro.getIndiceList().get(libro.getIndiceList().indexOf(indice)).setOrden(filaSuperior);
            libro.getIndiceList().get(libro.getIndiceList().indexOf(indiceSuperior)).setOrden(fila);

//            libro.getIndiceList().stream().forEach((Indice ind) -> System.out.println(String.format("DESC: %s, ORDEN: %s", ind.getDescripcion(),ind.getOrden())));
        }
    }//GEN-LAST:event_btnSubirIndiceActionPerformed

    private void btnBajarIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajarIndiceActionPerformed
        // TODO add your handling code here:
        int fila = tblIndice.getSelectedRow();
        int ultimaFila = indiceList.size() - 1;
        if (fila != -1 && fila < ultimaFila) {
            int filaInferior = fila + 1;
            Indice indice = indiceList.get(fila);
            Indice indiceInferior = indiceList.get(filaInferior);
            indice.setOrden(filaInferior);
            indiceInferior.setOrden(fila);
            indiceList.set(filaInferior, indice);
            indiceList.set(fila, indiceInferior);

            libro.getIndiceList().get(libro.getIndiceList().indexOf(indice)).setOrden(filaInferior);
            libro.getIndiceList().get(libro.getIndiceList().indexOf(indiceInferior)).setOrden(fila);

//            libro.getIndiceList().stream().forEach((Indice ind) -> System.out.println(String.format("DESC: %s, ORDEN: %s", ind.getDescripcion(),ind.getOrden())));
        }
    }//GEN-LAST:event_btnBajarIndiceActionPerformed

    private void btnEditorialNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialNuevoActionPerformed
        // TODO add your handling code here:
        EditorialCRUD editorialCRUD = new EditorialCRUD(this, true, NUEVO, new Editorial());
        editorialCRUD.setVisible(true);
        if (editorialCRUD.isAccionRealizada()) {
            bindEditorial();
            cboEditorial.setSelectedItem(editorialCRUD.getEditorial());
        }
    }//GEN-LAST:event_btnEditorialNuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadirAutor;
    private javax.swing.JButton btnAniadirIndice;
    private javax.swing.JButton btnAniadirTema;
    private javax.swing.JButton btnBajarIndice;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditorialNuevo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitarAutor;
    private javax.swing.JButton btnQuitarIndice;
    private javax.swing.JButton btnQuitarTema;
    private javax.swing.JButton btnSeccion;
    private javax.swing.JButton btnSubirIndice;
    private javax.swing.JComboBox<String> cboEditorial;
    private javax.swing.JComboBox<String> cboTipoLibro;
    private com.toedter.calendar.JDateChooser dcFechaPublicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAutor;
    private javax.swing.JPanel pnlAutorAccion;
    private javax.swing.JPanel pnlClasificacion1;
    private javax.swing.JPanel pnlEjemplar;
    private javax.swing.JPanel pnlIndice;
    private javax.swing.JPanel pnlIndiceAccion;
    private javax.swing.JPanel pnlIndiceOrden;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTema;
    private javax.swing.JPanel pnlTemaAccion;
    private javax.swing.JTabbedPane tabAutorTemaIndice;
    private javax.swing.JTabbedPane tabPrincipal;
    private org.jdesktop.swingx.JXTable tblAutor;
    private org.jdesktop.swingx.JXTable tblIndice;
    private org.jdesktop.swingx.JXTable tblTema;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtISBN10;
    private javax.swing.JTextField txtISBN13;
    private javax.swing.JTextField txtNroPaginas;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSeccion;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTomo;
    private javax.swing.JTextField txtVolumen;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        libroAutorControlador = LibroAutorControlador.getInstance();
        libroTemaControlador = LibroTemaControlador.getInstance();
        libroControlador = LibroControlador.getInstance();
        editorialControlador = EditorialControlador.getInstance();
        tipoLibroControlador = TipoLibroControlador.getInstance();
        indiceControlador = IndiceControlador.getInstance();

        BindingGroup bindGroup = new BindingGroup();

        libroAutorList = ObservableCollections.observableList(new ArrayList<LibroAutor>());
        libroTemaList = ObservableCollections.observableList(new ArrayList<LibroTema>());
        indiceList = ObservableCollections.observableList(new ArrayList<Indice>());
        ejemplarList = ObservableCollections.observableList(new ArrayList<Ejemplar>());

        JTableBinding bindTablaAutor = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, libroAutorList, tblAutor);
        BeanProperty pPaterno = BeanProperty.create("autor.paterno");
        BeanProperty pMaterno = BeanProperty.create("autor.materno");
        BeanProperty pNombres = BeanProperty.create("autor.nombres");
        bindTablaAutor.addColumnBinding(pNombres).setColumnName("Nombres").setEditable(false);
        bindTablaAutor.addColumnBinding(pPaterno).setColumnName("Ap. paterno").setEditable(false);
        bindTablaAutor.addColumnBinding(pMaterno).setColumnName("Ap. materno").setEditable(false);

        bindGroup.addBinding(bindTablaAutor);

        JTableBinding bindTablaTema = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, libroTemaList, tblTema);
        BeanProperty pTemaNombre = BeanProperty.create("tema.nombre");
        BeanProperty pTemaDescripcion = BeanProperty.create("tema.descripcion");
        bindTablaTema.addColumnBinding(pTemaNombre).setColumnName("Tema").setEditable(false);
        bindTablaTema.addColumnBinding(pTemaDescripcion).setColumnName("Descripción").setEditable(false);

        bindGroup.addBinding(bindTablaTema);

        JTableBinding bindIndice = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, indiceList, tblIndice);
        BeanProperty pIndiceDescripcion = BeanProperty.create("descripcion");
        bindIndice.addColumnBinding(pIndiceDescripcion).setColumnName("Índice").setEditable(false);

        bindGroup.addBinding(bindIndice);

        bindGroup.bind();
        bindComboBox();
    }

    private void volcarData(Libro seleccionado) {
        FormularioUtil.convertirAMayusculas(txtTitulo);
        
        seleccionado.setActivo(true);
        seleccionado.setTitulo(txtTitulo.getText());
        seleccionado.setIsbn10(txtISBN10.getText());
        seleccionado.setIsbn13(txtISBN13.getText());
        seleccionado.setEditorial((Editorial) cboEditorial.getSelectedItem());
        seleccionado.setNumeroEdicion(Integer.parseInt(txtEdicion.getText()));
        seleccionado.setNumeroPaginas(Integer.parseInt(txtNroPaginas.getText()));
        seleccionado.setSeccion(seccionSeleccionada);
        seleccionado.setNumero(txtNumero.getText().trim().isEmpty() ? -1 : Integer.parseInt(txtNumero.getText()));
        seleccionado.setVolumen(txtVolumen.getText().trim().isEmpty() ? -1 : Integer.parseInt(txtVolumen.getText()));
        seleccionado.setTomo(txtTomo.getText().trim().isEmpty() ? -1 : Integer.parseInt(txtTomo.getText()));
        seleccionado.setFechaPublicacion(dcFechaPublicacion.getDate());
        seleccionado.setTipoLibro((TipoLibro) cboTipoLibro.getSelectedItem());

        if (accion == NUEVO) {
            seleccionado.setFechaHoraCreacion(new Date());
        }
    }

    private void inicializar(Libro libro, int accion) {
        switch (accion) {
            case NUEVO:

                lblTitulo.setText("Registrar inf. de libro");
                btnCancelar.setText("Cancelar");
                break;
            case MODIFICAR:
                lblTitulo.setText("Modificar inf. de libro");
                btnCancelar.setText("Cancelar");
                break;
            case LEER:
                lblTitulo.setText("Ver inf. de libro");
                btnCancelar.setText("Cerrar");
                break;
        }

        libroControlador.setSeleccionado(libro);

        inicializarControles(accion);
        if (accion == MODIFICAR || accion == LEER) {
            llenarCampos(libro);
        }

    }

    private void llenarCampos(Libro libro) {
        txtTitulo.setText(libro.getTitulo());
        txtISBN10.setText(libro.getIsbn10());
        txtISBN13.setText(libro.getIsbn13());
        txtNroPaginas.setText(libro.getNumeroPaginas() + "");
        txtEdicion.setText(libro.getNumeroEdicion() + "");
        txtNumero.setText(libro.getNumero() == -1 ? "" : libro.getNumero() + "");
        txtVolumen.setText(libro.getVolumen() == -1 ? "" : libro.getVolumen() + "");
        txtTomo.setText(libro.getTomo() == -1 ? "" : libro.getTomo() + "");
        cboEditorial.setSelectedItem(libro.getEditorial());
        dcFechaPublicacion.setDate(libro.getFechaPublicacion());
        cboTipoLibro.setSelectedItem(libro.getTipoLibro());
        libroAutorList.addAll(libro.getLibroAutorList());
        libroTemaList.addAll(libro.getLibroTemaList());
        indiceList.addAll(libro.getIndiceList());
    }

    private void inicializarControles(int accion) {
        boolean leer = accion == LEER;
        boolean leerModificar = accion == LEER || accion == MODIFICAR;
        boolean nuevoModificar = accion == NUEVO || accion == MODIFICAR;

        this.btnEditar.setVisible(accion == LEER);
        this.btnEliminar.setVisible(leerModificar);
        this.btnGuardar.setVisible(nuevoModificar);

        this.txtTitulo.setEditable(!leer);
        this.txtISBN10.setEditable(!leer);
        this.txtISBN13.setEditable(!leer);
        this.cboEditorial.setEnabled(!leer);
        this.pnlAutorAccion.setVisible(!leer);
        this.btnSeccion.setVisible(!leer);
        this.txtNumero.setEditable(!leer);
        this.txtVolumen.setEditable(!leer);
        this.txtTomo.setEditable(!leer);
        this.txtEdicion.setEditable(!leer);

        this.tabPrincipal.setEnabledAt(1, accion != NUEVO);
    }

    private void bindComboBox() {
        bindEditorial();
        tipoLibroList = tipoLibroControlador.buscarTodos();
        JComboBoxBinding bindTipoLibro = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ, tipoLibroList, cboTipoLibro);
        bindTipoLibro.bind();

        cboTipoLibro.setRenderer(new AbstractListCellRenderer<TipoLibro>() {

            @Override
            public String getTexto(TipoLibro value) {
                return value.getNombre();
            }

            @Override
            public ImageIcon getIcono(TipoLibro value) {
                return null;
            }
        });
    }

    private void setSeccionSeleccionada(Seccion seccion) {
        this.seccionSeleccionada = seccion;

        if (this.seccionSeleccionada != null) {
            txtSeccion.setText(String.format("%s / %s", this.seccionSeleccionada.getMateria().getNombre(), this.seccionSeleccionada.getNombre()));
        }
    }

    private void bindEditorial() {
        editorialList = editorialControlador.buscarTodos();

        JComboBoxBinding bindComboEditorial = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ, editorialList, cboEditorial);
        bindComboEditorial.bind();
        
        cboEditorial.setRenderer(new AbstractListCellRenderer<Editorial>() {
            @Override
            public String getTexto(Editorial value) {
                return value.getNombre();
            }

            @Override
            public ImageIcon getIcono(Editorial value) {
                return null;
            }
        });
    }
}
