/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.sgb.vistas.dialogos;

import static com.biosis.sgb.Application.*;
import com.biosis.sgb.controlador.AutorControlador;
import com.biosis.sgb.controlador.LibroControlador;
import com.biosis.sgb.entidades.Autor;
import com.biosis.sgb.entidades.Editorial;
import com.biosis.sgb.entidades.Libro;
import com.biosis.sgb.entidades.LibroAutor;
import com.biosis.sgb.entidades.Seccion;
import com.biosis.sgb.entidades.Tema;
import com.personal.utiles.FormularioUtil;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Francis
 */
public class LibroSelect extends javax.swing.JDialog {

    /**
     * Creates new form AutorSelect
     */
//    private final LibroControlador libroControlador;
    private Autor autorSeleccionado;
    private Editorial editorialSeleccionada;
    private Seccion seccionSeleccionada;
    private Tema temaSeleccionado;

    private int paginaActual = 1;
    private int totalPaginas = 0;
    private int tamanioPagina = 0;

    private List<Libro> libroList;

    private Libro libro;

    private final LibroControlador libroControlador;

    public LibroSelect(Component parent, boolean modal) {
        super(JOptionPane.getFrameForComponent(parent), modal);
        this.libroControlador = LibroControlador.getInstance();
        initComponents();
        initComponents2();

        BusquedaLibro busquedaLibro = new BusquedaLibro();
        busquedaLibro.execute();
        this.setLocationRelativeTo(parent);
    }

    public Libro getLibro() {
        return libro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlSecundario = new javax.swing.JPanel();
        pnlBusqueda = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        lblEspere = new org.jdesktop.swingx.JXBusyLabel();
        chkAutor = new javax.swing.JCheckBox();
        chkEditorial = new javax.swing.JCheckBox();
        chkSeccion = new javax.swing.JCheckBox();
        chkTema = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        txtSeccion = new javax.swing.JTextField();
        btnSeccion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtTema = new javax.swing.JTextField();
        btnTema = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtEditorial = new javax.swing.JTextField();
        btnEditorial = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtAutor = new javax.swing.JTextField();
        btnAutor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        chkSoloDisponibles = new javax.swing.JCheckBox();
        pnlListado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibroList = new org.jdesktop.swingx.JXTable();
        pnlNavegacion2 = new javax.swing.JPanel();
        btnPrimero2 = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        spPagina = new javax.swing.JSpinner();
        txtTotal = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        cboTamanio = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(ESTILO5);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione un libro");
        jLabel1.setOpaque(true);
        pnlPrincipal.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        pnlSecundario.setLayout(new java.awt.BorderLayout());

        pnlBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        pnlBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parámetros de búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1));
        pnlBusqueda.setLayout(new java.awt.GridBagLayout());

        txtTitulo.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(txtTitulo, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        btnBuscar.setFont(ESTILO1);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Find/Find_16x16.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar);

        lblEspere.setText("Cargando resultados...");
        lblEspere.setFont(ESTILO1);
        jPanel2.add(lblEspere);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(jPanel2, gridBagConstraints);

        chkAutor.setFont(ESTILO1);
        chkAutor.setText("Autor:");
        chkAutor.setOpaque(false);
        chkAutor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkAutorStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkAutor, gridBagConstraints);

        chkEditorial.setFont(ESTILO1);
        chkEditorial.setText("Editorial:");
        chkEditorial.setOpaque(false);
        chkEditorial.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkEditorialStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkEditorial, gridBagConstraints);

        chkSeccion.setFont(ESTILO1);
        chkSeccion.setText("Sección:");
        chkSeccion.setOpaque(false);
        chkSeccion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkSeccionStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkSeccion, gridBagConstraints);

        chkTema.setFont(ESTILO1);
        chkTema.setText("Tema:");
        chkTema.setOpaque(false);
        chkTema.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkTemaStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkTema, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridBagLayout());

        txtSeccion.setEditable(false);
        txtSeccion.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(txtSeccion, gridBagConstraints);
        txtSeccion.setBorder(null);

        btnSeccion.setBackground(new java.awt.Color(204, 204, 255));
        btnSeccion.setFont(ESTILO1);
        btnSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeccionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(btnSeccion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlBusqueda.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.GridBagLayout());

        txtTema.setEditable(false);
        txtTema.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(txtTema, gridBagConstraints);
        txtSeccion.setBorder(null);

        btnTema.setBackground(new java.awt.Color(204, 204, 255));
        btnTema.setFont(ESTILO1);
        btnTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel4.add(btnTema, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlBusqueda.add(jPanel4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.GridBagLayout());

        txtEditorial.setEditable(false);
        txtEditorial.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(txtEditorial, gridBagConstraints);
        txtSeccion.setBorder(null);

        btnEditorial.setBackground(new java.awt.Color(204, 204, 255));
        btnEditorial.setFont(ESTILO1);
        btnEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel5.add(btnEditorial, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlBusqueda.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.GridBagLayout());

        txtAutor.setEditable(false);
        txtAutor.setFont(ESTILO2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel6.add(txtAutor, gridBagConstraints);
        txtSeccion.setBorder(null);

        btnAutor.setBackground(new java.awt.Color(204, 204, 255));
        btnAutor.setFont(ESTILO1);
        btnAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search/Search_16x16.png"))); // NOI18N
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        jPanel6.add(btnAutor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlBusqueda.add(jPanel6, gridBagConstraints);

        jLabel2.setFont(ESTILO1);
        jLabel2.setText("Título / ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        pnlBusqueda.add(jLabel2, gridBagConstraints);

        chkSoloDisponibles.setFont(ESTILO1);
        chkSoloDisponibles.setText("Mostrar sólo con ejemplares disponibles");
        chkSoloDisponibles.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlBusqueda.add(chkSoloDisponibles, gridBagConstraints);

        pnlSecundario.add(pnlBusqueda, java.awt.BorderLayout.PAGE_START);

        pnlListado.setBackground(new java.awt.Color(255, 255, 255));
        pnlListado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, ESTILO1        ));
        pnlListado.setLayout(new java.awt.BorderLayout());

        tblLibroList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLibroList.setFont(ESTILO2);
        tblLibroList.setHorizontalScrollEnabled(true);
        tblLibroList.setRowHeight(20);
        tblLibroList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblLibroListMouseReleased(evt);
            }
        });
        tblLibroList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblLibroListKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblLibroList);

        pnlListado.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlNavegacion2.setBackground(new java.awt.Color(255, 255, 255));
        pnlNavegacion2.setLayout(new java.awt.GridBagLayout());

        btnPrimero2.setText("<<");
        btnPrimero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimero2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        pnlNavegacion2.add(btnPrimero2, gridBagConstraints);

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        pnlNavegacion2.add(btnAnterior, gridBagConstraints);

        spPagina.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spPagina.setMinimumSize(new java.awt.Dimension(60, 20));
        spPagina.setPreferredSize(new java.awt.Dimension(60, 20));
        spPagina.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spPaginaStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        pnlNavegacion2.add(spPagina, gridBagConstraints);

        txtTotal.setEditable(false);
        txtTotal.setColumns(3);
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        pnlNavegacion2.add(txtTotal, gridBagConstraints);

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        pnlNavegacion2.add(btnSiguiente, gridBagConstraints);

        btnUltimo.setText(">>");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        pnlNavegacion2.add(btnUltimo, gridBagConstraints);

        cboTamanio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "15", "20", "25", "40", "50" }));
        cboTamanio.setMinimumSize(new java.awt.Dimension(53, 24));
        cboTamanio.setPreferredSize(new java.awt.Dimension(53, 24));
        cboTamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTamanioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        pnlNavegacion2.add(cboTamanio, gridBagConstraints);

        pnlListado.add(pnlNavegacion2, java.awt.BorderLayout.SOUTH);

        pnlSecundario.add(pnlListado, java.awt.BorderLayout.CENTER);

        pnlPrincipal.add(pnlSecundario, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        BusquedaLibro busquedaLibro = new BusquedaLibro();
        busquedaLibro.execute();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void chkAutorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkAutorStateChanged
        // TODO add your handling code here:
        checkboxes();
    }//GEN-LAST:event_chkAutorStateChanged

    private void chkEditorialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkEditorialStateChanged
        // TODO add your handling code here:
        checkboxes();
    }//GEN-LAST:event_chkEditorialStateChanged

    private void chkSeccionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkSeccionStateChanged
        // TODO add your handling code here:
        checkboxes();
    }//GEN-LAST:event_chkSeccionStateChanged

    private void chkTemaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkTemaStateChanged
        // TODO add your handling code here:
        checkboxes();
    }//GEN-LAST:event_chkTemaStateChanged

    private void btnSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeccionActionPerformed
        // TODO add your handling code here:
        SeccionSelect seccionSelect = new SeccionSelect(this, true);
        seccionSelect.setVisible(true);
        this.seccionSeleccionada = seccionSelect.getSeccion();

        if (this.seccionSeleccionada != null) {
            txtSeccion.setText("  " + this.seccionSeleccionada.getNombre());
        }
    }//GEN-LAST:event_btnSeccionActionPerformed

    private void btnTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemaActionPerformed
        // TODO add your handling code here:
        TemaSelect temaSelect = new TemaSelect(this, true);
        temaSelect.setVisible(true);
        this.temaSeleccionado = temaSelect.getTema();

        if (this.temaSeleccionado != null) {
            txtTema.setText("  " + temaSeleccionado.getNombre());
        }
    }//GEN-LAST:event_btnTemaActionPerformed

    private void btnEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialActionPerformed
        // TODO add your handling code here:
        EditorialSelect editorialSelect = new EditorialSelect(this, true);
        editorialSelect.setVisible(true);
        this.editorialSeleccionada = editorialSelect.getEditorial();
        if (this.editorialSeleccionada != null) {
            txtEditorial.setText("  " + this.editorialSeleccionada.getNombre());
        }
    }//GEN-LAST:event_btnEditorialActionPerformed

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        // TODO add your handling code here:
        AutorSelect autorSelect = new AutorSelect(this, true);
        autorSelect.setVisible(true);
        this.autorSeleccionado = autorSelect.getAutor();
        if (this.autorSeleccionado != null) {
            txtAutor.setText(String.format("  %s, %s", autorSeleccionado.getPaterno(), autorSeleccionado.getNombres()));
        }
    }//GEN-LAST:event_btnAutorActionPerformed

    private void btnPrimero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimero2ActionPerformed
        // TODO add your handling code here:
        primero();
    }//GEN-LAST:event_btnPrimero2ActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        anterior();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void spPaginaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spPaginaStateChanged
        // TODO add your handling code here:
        this.seleccionPagina();
    }//GEN-LAST:event_spPaginaStateChanged

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        siguiente();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        // TODO add your handling code here:
        ultimo();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void cboTamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTamanioActionPerformed
        // TODO add your handling code here:
        this.paginaActual = 1;
        buscar();
        this.actualizarControlesNavegacion();
    }//GEN-LAST:event_cboTamanioActionPerformed

    private void tblLibroListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibroListMouseReleased
        // TODO add your handling code here:
        int conteo = evt.getClickCount();
        if (conteo == 2) {
            int fila = tblLibroList.getSelectedRow();
            this.libro = this.libroList.get(fila);
            this.dispose();
        }
    }//GEN-LAST:event_tblLibroListMouseReleased

    private void tblLibroListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLibroListKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int fila = tblLibroList.getSelectedRow();
            this.libro = this.libroList.get(fila);
            this.dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP && tblLibroList.getSelectedRow() == 0) {
            txtTitulo.requestFocus();
        }
    }//GEN-LAST:event_tblLibroListKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditorial;
    private javax.swing.JButton btnPrimero2;
    private javax.swing.JButton btnSeccion;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnTema;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox cboTamanio;
    private javax.swing.JCheckBox chkAutor;
    private javax.swing.JCheckBox chkEditorial;
    private javax.swing.JCheckBox chkSeccion;
    private javax.swing.JCheckBox chkSoloDisponibles;
    private javax.swing.JCheckBox chkTema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXBusyLabel lblEspere;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JPanel pnlListado;
    private javax.swing.JPanel pnlNavegacion2;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSecundario;
    private javax.swing.JSpinner spPagina;
    private org.jdesktop.swingx.JXTable tblLibroList;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtSeccion;
    private javax.swing.JTextField txtTema;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        lblEspere.setVisible(false);
        this.libroList = ObservableCollections.observableList(new ArrayList<Libro>());
        //procedemos a bindear
        BindingGroup grupo = new BindingGroup();

        BeanProperty bTitulo = BeanProperty.create("titulo");
        BeanProperty bIsbn10 = BeanProperty.create("isbn10");
        BeanProperty bIsbn13 = BeanProperty.create("isbn13");
        BeanProperty bEjemplarTotal = BeanProperty.create("ejemplarTotal");
        BeanProperty bEjemplarDisponible = BeanProperty.create("ejemplarDisponible");
        BeanProperty bAutores = BeanProperty.create("libroAutorList");
        BeanProperty bMateria = BeanProperty.create("seccion.materia.nombre");
        BeanProperty bSeccion = BeanProperty.create("seccion.nombre");
        JTableBinding bindeoTabla = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, libroList, tblLibroList);
        bindeoTabla.addColumnBinding(bTitulo).setColumnName("Titulo").setEditable(false);
        bindeoTabla.addColumnBinding(bAutores).setColumnName("Autor(es)").setEditable(false).setColumnClass(List.class);
        bindeoTabla.addColumnBinding(bMateria).setColumnName("Materia").setEditable(false);
        bindeoTabla.addColumnBinding(bSeccion).setColumnName("Sección").setEditable(false);
        bindeoTabla.addColumnBinding(bIsbn10).setColumnName("ISBN 10").setEditable(false);
        bindeoTabla.addColumnBinding(bIsbn13).setColumnName("ISBN 13").setEditable(false);
        bindeoTabla.addColumnBinding(bEjemplarTotal).setColumnName("Total").setEditable(false);
        bindeoTabla.addColumnBinding(bEjemplarDisponible).setColumnName("Disponibles").setEditable(false);

        grupo.addBinding(bindeoTabla);
        grupo.bind();

        tblLibroList.getColumn(1).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                if (value != null) {
                    if (value instanceof List) {
                        List<LibroAutor> listado = (List) value;
                        StringBuilder sb = new StringBuilder();
                        listado.stream().forEach(la -> sb.append(String.format("%s %s, ", la.getAutor().getPaterno(), la.getAutor().getNombres())));
                        value = sb.toString().substring(0, sb.toString().length() - 2);
                    }

                }
                return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }

    private void controles(boolean busqueda) {
        FormularioUtil.activarComponente(pnlBusqueda, !busqueda);
//        FormularioUtil.activarComponente(pnlAcciones, !busqueda);
    }

    //cambiamos acorde a lo que se requiere
    private void buscar() {
//        String busqueda = txtBusqueda.getText();
        tamanioPagina = Integer.parseInt(cboTamanio.getSelectedItem().toString());

        //AQUI LO PASAMOS A UN SWING WORKER
        libroList.clear();

        libroList.addAll(this.listar(paginaActual, tamanioPagina));

        tblLibroList.packAll();
    }

    private List<Libro> listar(int pagina, int tamanio) {
        int total = 0;
        String txtPatron = txtTitulo.getText();
        total = libroControlador.contarMultiple(
                chkAutor.isSelected() ? autorSeleccionado : null,
                chkEditorial.isSelected() ? editorialSeleccionada : null,
                chkSeccion.isSelected() ? seccionSeleccionada : null,
                chkTema.isSelected() ? temaSeleccionado : null,
                txtPatron.trim().toUpperCase(),
                chkSoloDisponibles.isSelected());

        if (total % tamanio == 0) {
            totalPaginas = total / tamanio;
        } else {
            totalPaginas = (total / tamanio) + 1;
        }

        if (totalPaginas == 0) {
            totalPaginas = 1;
        }

        int desde = (pagina - 1) * tamanio;

        return libroControlador.consultaMultiple(
                chkAutor.isSelected() ? autorSeleccionado : null,
                chkEditorial.isSelected() ? editorialSeleccionada : null,
                chkSeccion.isSelected() ? seccionSeleccionada : null,
                chkTema.isSelected() ? temaSeleccionado : null,
                txtPatron.trim().toUpperCase(),
                chkSoloDisponibles.isSelected(),
                desde, tamanio);
    }

    private void siguiente() {
        paginaActual++;
        buscar();
        this.actualizarControlesNavegacion();
    }

    private void ultimo() {
        paginaActual = totalPaginas;
        buscar();
        this.actualizarControlesNavegacion();
    }

    private void primero() {
        paginaActual = 1;
        buscar();
        this.actualizarControlesNavegacion();
    }

    private void anterior() {
        paginaActual--;
        buscar();
        this.actualizarControlesNavegacion();
    }

    private void seleccionPagina() {
        paginaActual = (int) spPagina.getValue();
        buscar();
        this.actualizarControlesNavegacion();
    }

    private void actualizarControlesNavegacion() {
        spPagina.setValue(paginaActual);
        txtTotal.setText(totalPaginas + "");

        SpinnerNumberModel modeloSP = (SpinnerNumberModel) spPagina.getModel();
        Comparable<Integer> maximo = totalPaginas;
        modeloSP.setMaximum(maximo);

        this.btnSiguiente.setEnabled(paginaActual != totalPaginas);
        this.btnUltimo.setEnabled(paginaActual != totalPaginas);

        this.btnAnterior.setEnabled(paginaActual != 1);
        this.btnPrimero2.setEnabled(paginaActual != 1);
    }

    private void checkboxes() {
        txtAutor.setEditable(false);
        txtEditorial.setEditable(false);
        txtSeccion.setEditable(false);
        txtTema.setEditable(false);

        btnAutor.setEnabled(chkAutor.isSelected());
        btnEditorial.setEnabled(chkEditorial.isSelected());
        btnSeccion.setEnabled(chkSeccion.isSelected());
        btnTema.setEnabled(chkTema.isSelected());
    }

    private class BusquedaLibro extends SwingWorker<Double, Void> {

        @Override
        protected Double doInBackground() throws Exception {
            controles(true);
            lblEspere.setEnabled(true);
            lblEspere.setVisible(true);
            lblEspere.setBusy(true);
            paginaActual = 1;
            buscar();
            actualizarControlesNavegacion();
            return 0.0;
        }

        @Override
        protected void done() {
            controles(false);
            lblEspere.setBusy(false);
            lblEspere.setVisible(false);
        }

    }
}
